apiVersion: v1
kind: ServiceAccount
metadata:
  name: restarter
---
apiVersion: v1
kind: Secret
metadata:
  name: restarter
  annotations:
    kubernetes.io/service-account.name: restarter
type: kubernetes.io/service-account-token
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: restarter
rules:
  - apiGroups: [apps]
    resources: [deployments]
    resourceNames: [inoa-cloud-dev]
    verbs: [get, patch]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: restarter
subjects:
  - kind: ServiceAccount
    name: restarter
roleRef:
  kind: Role
  name: restarter
  apiGroup: rbac.authorization.k8s.io
