# https://docs.k3s.io/installation/private-registry
mirrors:
  "*":
  docker.io:
    endpoint: [http://registry.woodpecker.svc]
    rewrite: {"^(.*)$": docker.io/$1}
  ghcr.io:
    endpoint: [http://registry.woodpecker.svc]
    rewrite: {"^(.*)$": ghcr.io/$1}
