commonLabels:
  app.kubernetes.io/part-of: inoa
  app.kubernetes.io/name: inoa

resources:
  - cloudsql.yaml
  - certificate.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: inoa-env
    literals:
      - MICRONAUT_ENVIRONMENTS=postgres
      - MICRONAUT_SECURITY_TOKEN_JWT_SIGNATURES_JWKS_KEYCLOAK_URL=http://keycloak.infrastructure:8080/realms/inoa/protocol/openid-connect/certs
      - MICRONAUT_HTTP_SERVICES_HAWKBIT_URL=http://hawkbit
      - DATASOURCES_DEFAULT_HOST=sqlproxy.infrastructure
      - DATASOURCES_DEFAULT_DATABASE=inoa-<patched>
      - DATASOURCES_DEFAULT_USERNAME=inoa-<patched>
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_ORGANISATION=inoa
      - INFLUXDB_BUCKET=default
      - INOA_MQTT_TLS_GENERATE_KEY=false
      - INOA_MQTT_TLS_KEY=/tls/tls.key
      - INOA_MQTT_TLS_CERT=/tls/tls.crt
      - INOA_MQTT_DATA_PATH=/moquette
      # custom log levels
      - LOGGER_LEVELS_IO_INOA=TRACE
      - LOGGER_LEVELS_ORG_APACHE_KAFKA=WARN

secretGenerator:
  - name: inoa-env
    literals:
      - DATASOURCES_DEFAULT_PASSWORD=<patched>
      - INFLUXDB_TOKEN=<patched>
