labels:
  - pairs:
      app.kubernetes.io/name: inoa
      app.kubernetes.io/technology: micronaut

resources:
  - certificate.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: inoa-env
    literals:
      # INOA Settings
      - INOA_DOMAIN=${inoa_domain}
      - INOA_MQTT_TLS_GENERATE_KEY=false
      - INOA_MQTT_TLS_KEY=/tls/tls.key
      - INOA_MQTT_TLS_CERT=/tls/tls.crt
      - INOA_MQTT_DATA_PATH=/moquette
      # Database settings
      - DATASOURCES_DEFAULT_HOST=postgres
      - DATASOURCES_DEFAULT_DATABASE=inoa
      - DATASOURCES_DEFAULT_USERNAME=inoa
      # Kafka settings
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      # Influx settings
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_ORGANISATION=inoa
      - INFLUXDB_BUCKET=inoa
      # Log levels
      - LOGGER_LEVELS_IO_INOA=INFO
      - LOGGER_LEVELS_ORG_APACHE_KAFKA=WARN
