apiVersion: apps/v1
kind: Deployment
metadata:
  name: measurement-telemetry-translator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: measurement-telemetry-translator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: measurement-telemetry-translator
    spec:
      containers:
        - name: measurement-telemetry-translator
          image: ghcr.io/inoa-io/measurement-telemetry-translator
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: inoa-environment
                optional: true
            - configMapRef:
                name: measurement-telemetry-translator-environment
          ports:
            - name: http
              containerPort: 8080
            - name: managment
              containerPort: 8090
          startupProbe:
            httpGet:
              path: /endpoints/health
              port: managment
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /endpoints/health/readiness
              port: managment
          livenessProbe:
            httpGet:
              path: /endpoints/health/liveness
              port: managment
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            readOnlyRootFilesystem: false
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 5
