labels:
  - pairs:
      app.kubernetes.io/name: influxdb
      app.kubernetes.io/technology: rust

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

configMapGenerator:
  - name: influxdb-env
    literals:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=inoa
      - DOCKER_INFLUXDB_INIT_BUCKET=inoa
      - DOCKER_INFLUXDB_INIT_RETENTION=0s
      - INFLUXD_BOLT_PATH=/var/lib/influxdb2/influxd.bolt
      - INFLUXD_ENGINE_PATH=/var/lib/influxdb2
