apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: influxdb
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  location: europe-west3-c
  resourceID: <patched>
  size: 5
  type: pd-standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb
spec:
  gcePersistentDisk:
    pdName: <patched>
    fsType: ext4
  storageClassName: standard
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
spec:
  volumeName: influxdb
  storageClassName: standard
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
