namespace: inoa-prod

commonLabels:
  app.kubernetes.io/part-of: inoa
  app.kubernetes.io/env: prod

images:
  - name: docker.io/library/influxdb
    newTag: 2.7.11
  - name: docker.io/redpandadata/console
    newTag: v2.8.2
  - name: docker.io/hawkbit/hawkbit-update-server
    newTag: 0.3.0M8
  - name: ghcr.io/grayc-de/kafka
    newTag: 3.6.1
  - name: ghcr.io/inoa-io/inoa
    newTag: release

resources:
  - ../../base/fluxcd
  - public/redirect
  - public/documentation
  - hawkbit
  - influxdb
  - kafka
  - kafka-console
  - inoa

# scale prod down to 0 to avoid costs
patches:
  - target:
      kind: StatefulSet
      name: kafka
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: inoa
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: kafka-console
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: influxdb
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: hawkbit
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
