namespace: inoa-prod

commonLabels:
  app.kubernetes.io/part-of: inoa
  app.kubernetes.io/env: prod

images:
  - name: docker.io/library/influxdb
    newTag: 2.7.5
  - name: docker.io/obsidiandynamics/kafdrop
    newTag: 4.0.1
  - name: docker.io/provectuslabs/kafka-ui
    newTag: v0.7.1
  - name: docker.io/redpandadata/console
    newTag: v2.4.3
  - name: ghcr.io/grayc-de/kafka
    newTag: 3.6.1
  - name: ghcr.io/inoa-io/fleet
    newTag: release
  - name: ghcr.io/inoa-io/measurement
    newTag: release

resources:
  - ../../base/fluxcd
  - public/redirect
  - public/documentation
  - influxdb
  - kafka
  - kafka-console
  - kafka-ui
  - kafdrop
  - inoa-fleet
  - inoa-measurement

configMapGenerator:
  - name: inoa-env
    literals:
      # TODO set as default in all deployments
      - ENDPOINTS_ALL_PORT=8090
      - LOGGER_LEVELS_IO_INOA=TRACE
      - LOGGER_LEVELS_ORG_APACHE_KAFKA=WARN

# scale prod down to 0 to avoid costs
patches:
  - target:
      kind: StatefulSet
      name: kafka
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: fleet
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: measurement
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: kafka-console
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: influxdb
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
