version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    assignees:
      - sschnabe
      - rpahli
      - fabian-schlegel
    ignore:
      - dependency-name: org.keycloak.bom:*           # keycloak is an external dependency
      - dependency-name: org.eclipse.hono:*           # hono is an external dependency
      - dependency-name: org.springframework.boot:*   # spring version aligned with version from hono-pom
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
