*

!api/src/main
!api/gen/main
!api/pom.xml
!api/openapi.yaml
!service/src/main
!service/pom.xml
!src/main
!lombok.config
!pom.xml

!app/src
!app/.yarnrc.yml
!app/yarn.lock
!app/angular.json
!app/package.json
!app/tsconfig.json
!app/tsconfig.app.json
