### GET request to example server
PATCH http://inoa.192.168.20.10.nip.io:8080/gateways/ISNJ01-000000000001 PATCH
Content-Type: application/json
Accept: application/json
Authorization: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJuNHBYdlcxMzJkVmVCLVQ2WlByZ0Z3NUQ4RkJ5VTBPT082cFRyU1l6WkMwIn0.eyJleHAiOjE3MjU3MjI4OTYsImlhdCI6MTcyNTYzNjQ5NiwianRpIjoiZTRlYTkwZmEtZTIyOC00YTlkLWIyZjctNDI3ZTI1N2ZiM2I0IiwiaXNzIjoiaHR0cDovL2tleWNsb2FrLjE5Mi4xNjguMjAuMTAubmlwLmlvOjgwODAvcmVhbG1zL2lub2EiLCJhdWQiOiJpbm9hLXJlZ2lzdHJ5Iiwic3ViIjoiY2E0MGE4MTYtZDgxOC00NDdjLWIyYzMtZDlhMmQwMTYyMTNjIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiaW5vYS1tY25vaXplIiwic2NvcGUiOiIiLCJ0ZW5hbnRzIjoiaW5vYSIsImNsaWVudEhvc3QiOiIxOTIuMTY4LjIwLjEwIiwiY2xpZW50QWRkcmVzcyI6IjE5Mi4xNjguMjAuMTAiLCJjbGllbnRfaWQiOiJpbm9hLW1jbm9pemUifQ.jO8xG_e4p1ANQOK1BLeRoOGtRZ1x27xywFJHavRi-iLNkuFdixJxL6RkWD6qMkyEwc-u_eP2uCYO2_5yvfhNZL09GaJ95MLiXURaQ8e8OMeSFj9RDFcmTfXJwShR6tcdfIRsAcjzQZmJW_d0X__VokvRU-SJUA9lVolMQWp_fshgpWl8KmEPPL2-alBvFnNK32dRcTmxZ-dkMGj2F8gOM4ZNGk3oncewRvIRtJgNJFI7PdrICUOrtbyVH75FBg0RyrrWZkh0otUUwAk72f7wPEoSXeMeVudCYKi90olMJcSOhHNtL2kf5OWpT97qcQjtq0lw2A3fLEUdTalDx0B9gw"

{ "enabled": true }
