#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL

    CREATE DATABASE "fleet";
    CREATE USER "fleet" WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD_FLEET';
    GRANT ALL PRIVILEGES ON DATABASE "fleet" TO "fleet";

    CREATE DATABASE "measurement";
    CREATE USER "measurement" WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD_MEASUREMENT';
    GRANT ALL PRIVILEGES ON DATABASE "measurement" TO "measurement";

    CREATE DATABASE "hawkbit";
    CREATE USER "hawkbit" WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD_HAWKBIT';
    GRANT ALL PRIVILEGES ON DATABASE "hawkbit" TO "hawkbit";

EOSQL
