micronaut:
  application:
    name: ${project.artifactId}
    version: ${project.version}

  ## see https://docs.micronaut.io/latest/guide/index.html#staticResources
  router:
    static-resources:
      openapi:
        paths: classpath:openapi
        mapping: /openapi/**

  ## see https://docs.micronaut.io/latest/guide/index.html#cors
  server:
    cors:
      enabled: true
      default:
        allowedMethods:
          - GET
          - POST
          - PUT
          - DELETE

  security:

    ## see https://micronaut-projects.github.io/micronaut-security/latest/guide/#interceptUrlMap
    intercept-url-map:
      - pattern: /endpoints/**
        access: isAnonymous()
      - pattern: /openapi/**
        access: isAnonymous()
      - pattern: /**
        access: isAuthenticated()

  # see https://micronaut-projects.github.io/micronaut-data/latest/guide/configurationreference.html
  data:
    pageable:
      max-page-size: 100
      default-page-size: 10

## see https://docs.micronaut.io/latest/guide/index.html#providedEndpoints
endpoints:
  all:
    port: 8090
    path: /endpoints
    sensitive: false
  health:
    details-visible: ANONYMOUS
  loggers:
    write-sensitive: false

## see https://docs.micronaut.io/latest/guide/index.html#jsonBinding
jackson:
  bean-introspection-module: true
  serialization:
    writeDatesAsTimestamps: false

## see https://micronaut-projects.github.io/micronaut-sql/latest/guide/#jdbc
datasources:
  default:
    url: jdbc:h2:mem:${datasources.default.database};MODE=PostgreSQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    database: gateway-registry
    username: gateway-registry
    password: changeMe
    dialect: POSTGRES

## see https://micronaut-projects.github.io/micronaut-flyway/latest/guide/index.html#additionalConfig
flyway:
  datasources:
    default:
      locations: classpath:database

## Custom log configuration
logger:
  levels:
    io.micronaut.retry.intercept.RecoveryInterceptor: "OFF"
