resources:
  - ../../../base/kafka
  - pvc.yaml

patches:
  - target:
      kind: StatefulSet
    patch: |-
      - op: test
        path: /spec/template/spec/initContainers/1/env/0/name
        value: KAFKA_CLUSTER_ID
      - op: replace
        path: /spec/template/spec/initContainers/1/env/0/value
        value: NjRjODI4MjJiMDExNDExZG
      - op: test
        path: /spec/template/spec/initContainers/0/env/0/name
        value: KAFKA_REPLICAS
      - op: replace
        path: /spec/template/spec/initContainers/0/env/0/value
        value: "1"
      - op: replace
        path: /spec/replicas
        value: 1
