namespace: grayc-inoa-qas

labels:
  - pairs:
      app.kubernetes.io/part-of: inoa
      app.kubernetes.io/env: ${inoa_env}

images:
  - name: docker.io/library/influxdb
    newTag: "2.7.11"
  - name: docker.io/grafana/grafana
    newTag: "10.2.4"
  - name: ghcr.io/inoa-io/inoa
    newTag: "snapshot"

resources:
  - namespace.yaml
  - ../../base/fluxcd
  - service-account
  - postgres
  - keycloak
  - hawkbit
#  - influxdb
  - kafka
  - kafka-console
  - grafana
  - swagger-ui
#  - inoa
