micronaut:

  ## see https://docs.micronaut.io/latest/guide/index.html#staticResources
  router:
    static-resources:
      openapi:
        paths: classpath:openapi
        mapping: /openapi/**

## see https://docs.micronaut.io/latest/guide/index.html#providedEndpoints
endpoints:
  all:
    port: 8090
    path: /endpoints
    sensitive: false
  health:
    details-visible: ANONYMOUS

## see https://docs.micronaut.io/latest/guide/index.html#jsonBinding
jackson:
  bean-introspection-module: true
  serialization:
    writeDatesAsTimestamps: false

## see https://micronaut-projects.github.io/micronaut-sql/latest/guide/#jdbc
datasources:
  default:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:${datasources.default.database};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE
    database: gateway-registry
    username: gateway-registry
    password: changeMe
    dialect: H2

## see https://micronaut-projects.github.io/micronaut-flyway/latest/guide/index.html#additionalConfig
flyway:
  datasources:
    default:
      locations: classpath:database/${datasources.default.dialect}
