micronaut:

  ## see https://docs.micronaut.io/latest/guide/index.html#staticResources
  router:
    static-resources:
      openapi:
        paths: classpath:openapi
        mapping: /openapi/**

  ## see https://docs.micronaut.io/latest/guide/index.html#cors
  server:
    cors:
      enabled: false

  ## see https://micronaut-projects.github.io/micronaut-security/latest/guide/index.html
  security:
    intercept-url-map:
    # endpoints should be available for operations (should not exposed to extern)
    - pattern: /endpoints/**
      access: isAnonymous()
    # openapi should be available for everybody
    - pattern: /openapi/**
      access: isAnonymous()
    # auth endpoints should be available for everybody
    - pattern: /auth/keys
      access: isAnonymous()
    - pattern: /auth/token
      access: isAnonymous()
    # secure everything else
    - pattern: /**
      access: isAuthenticated()

## see https://docs.micronaut.io/latest/guide/index.html#providedEndpoints
endpoints:
  all:
    path: /endpoints
    sensitive: false
  health:
    details-visible: ANONYMOUS

## see https://docs.micronaut.io/latest/guide/index.html#jsonBinding
jackson:
  bean-introspection-module: true
  serialization:
    writeDatesAsTimestamps: false

## see https://micronaut-projects.github.io/micronaut-sql/latest/guide/#jdbc
datasources:
  default:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:${datasources.default.database};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE
    database: gateway-registry
    username: micronaut
    password: changeMe
    dialect: H2

## see https://micronaut-projects.github.io/micronaut-flyway/latest/guide/index.html#additionalConfig
flyway:
  datasources:
    default:
      locations: classpath:database/${datasources.default.dialect}
