micronaut:

  # open management for usage without token
  security:
    intercept-url-map:
    - pattern: /**
      access: isAnonymous()

  ## see https://docs.micronaut.io/latest/guide/index.html#cors
  server:
    cors:
      enabled: true

## see https://docs.micronaut.io/latest/guide/index.html#jsonBinding
jackson:
  serialization:
    indentOutput: true

registry:

  # set config values
  config-uri: https://kokuwa.io/consul
  config-type: consul

  # enable long living tokens based on random RSA key
  auth:
    expiration-duration: P1d
    generate-key: true
    issuer: ${random.uuid}

  # enable eternal token
  gateway.token.issued-at-threshold: null

logger:
  levels:
    io.kokuwa: TRACE
