apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: kafka-0
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  location: europe-west3-c
  resourceID: inoa-dev-kafka-0
  size: 1
  type: pd-standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: inoa-dev-kafka-0
spec:
  gcePersistentDisk:
    pdName: inoa-dev-kafka-0
    fsType: ext4
  storageClassName: standard
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-kafka-0
spec:
  volumeName: inoa-dev-kafka-0
  storageClassName: standard
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
