micronaut:
  application:
    name: ${project.artifactId}
    version: ${project.version}

## see https://docs.micronaut.io/latest/guide/index.html#providedEndpoints
endpoints:
  all:
    path: /endpoints
    sensitive: false
  health:
    details-visible: ANONYMOUS
  loggers:
    write-sensitive: false

## Translator
inoa.measurement.translator:
  types:

    # example for tests
    - name: example
      sensors:
        - name: number                # matches urn:example:<id>:number
          converter: number
        - name: number-with-modifier  # matches urn:example:<id>:number-10
          converter: number
          modifier: 10
        - pattern: ^abc[0-9]$         # matches urn:example:<id>:abc4
          converter: number
        - name: json                  # matches urn:example:<id>:json
          converter: json
        - name: modbus                # matches urn:example:<id>:modbus
          converter: modbus
        - name: modbus-with-modifier  # matches urn:example:<id>:modbus-with-modifier
          converter: modbus
          modifier: 10

    - name: shplg-s
      sensors:
        - name: status
          converter: json-path
          config:
            power: "$.meters[:1].power"
            work: "$.meters[:1].total"
            temperature: "$.temperature"

    - name: shellyht
      sensors:
        - name: status
          converter: json-path
          config:
            temperature: "$.tmp.value"
            humidity: "$.hum.value"
            battery: "$.bat.value"

    # source: https://www.dzg.de/fileadmin/dzg/content/downloads/produkte-zaehler/dvh4013/DZG_Modbus_Protocol.pdf
    - name: dvh4013
      sensors:
        - name: "0x4000"   # The current total tariff rate import active energy
          modifier: 1      # 3 decimal places, the unit kWh
          converter: modbus
          ext:
            label: work_in
            obis: 1-0:1.8.0*255
            unit: watthour
        - name: "0x4100"   # The current tariff rate 1 export active demand
          modifier: 1      # 3 decimal places, the unit kWh
          converter: modbus
          ext:
            label: work_out
            obis: 1-0:2.8.0*255
            unit: watthour
        - name: "0x0000"   # The total import active power
          modifier: 0.1    # 1 decimal places, the unit W
          converter: modbus
          ext:
            label: power_in
            unit: watt
        - name: "0x0002"   # The total export active power
          modifier: 0.1    # 1 decimal places, the unit W
          converter: modbus
          ext:
            label: power_out
            unit: watt
        - name: "0x0004"   # L1 voltage effective value
          modifier: 0.01   # 2 decimal places, the unit V
          converter: modbus
          ext:
            label: l1_voltage
            unit: volt
        - name: "0x0006"   # L2 voltage effective value
          modifier: 0.01   # 2 decimal places, the unit V
          converter: modbus
          ext:
            label: l2_voltage
            unit: volt
        - name: "0x0008"   # L3 voltage effective value
          modifier: 0.01   # 2 decimal places, the unit V
          converter: modbus
          ext:
            label: l3_voltage
            unit: volt
        - name: "0x000A"   # L1 current effective value
          modifier: 0.001  # 3 decimal places, the unit A
          converter: modbus
          ext:
            label: l1_current
            unit: ampere
        - name: "0x000C"   # L2 current effective value
          modifier: 0.001  # 3 decimal places, the unit A
          converter: modbus
          ext:
            label: l2_current
            unit: ampere
        - name: "0x000E"   # L3 current effective value
          modifier: 0.001  # 3 decimal places, the unit A
          converter: modbus
          ext:
            label: l3_current
            unit: ampere
        - name: "0x0010"   # Power factor
          modifier: 0.001  # 3 decimal places, unitless
          converter: modbus
          ext:
            label: power_factor
        - name: "0x0012"   # Frequency
          modifier: 0.001  # 3 decimal places, the unit Hz
          converter: modbus
          ext:
            label: frequency
            unit: hertz
        - name: "0x0014"   # The total import demand
          modifier: 0.1    # 4 decimal places, the unit kW
          converter: modbus
          ext:
            label: work_in
            unit: watt
        - name: "0x0016"   # The total export demand
          modifier: 0.1    # 4 decimal places, the unit kW
          converter: modbus
          ext:
            label: work_out
            unit: watt
        - name: "0x0018"   # L1 voltage threshold
          modifier: 0.001  # 3 decimal places, the unit %
          converter: modbus
          ext:
            label: l1_voltage_threshold
            unit: percent
        - name: "0x001A"   # L2 voltage threshold
          modifier: 0.001  # 3 decimal places, the unit %
          converter: modbus
          ext:
            label: l2_voltage_threshold
            unit: percent
        - name: "0x001C"   # L3 voltage threshold
          modifier: 0.001  # 3 decimal places, the unit %
          converter: modbus
          ext:
            label: l3_voltage_threshold
            unit: percent

    # source: Fabian Schlegel
    - name: satellite
      sensors:
        - name: memory_heap   # memory heap
          converter: number
          ext:
            unit: byte
        - name: memory_free   # memory free
          converter: number
          ext:
            unit: byte
        - name: reset_reason  # reason of last restart
          converter: number
        - name: reset_count   # count of restarts since manufacturing
          converter: number
