apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: inoa-dev
spec:
  secretName: tls-inoa-dev
  dnsNames: [dev.inoa.io]
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: istio-system
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
