/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Subject for cloud events.
 */
export type CloudEventTypeVO = 'io.inoa.log.emitted' | 'io.inoa.measurement.telemetry';

export const CloudEventTypeVO = {
    LogEmitted: 'io.inoa.log.emitted' as CloudEventTypeVO,
    MeasurementTelemetry: 'io.inoa.measurement.telemetry' as CloudEventTypeVO
};

