/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Subject for cloud events.
 */
export const CloudEventSubjectVO = {
    Telemetry: 'telemetry'
} as const;
export type CloudEventSubjectVO = typeof CloudEventSubjectVO[keyof typeof CloudEventSubjectVO];

