/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Subject for cloud events.
 */
export const CloudEventTypeVO = {
    IoInoaLogEmitted: 'io.inoa.log.emitted',
    IoInoaMeasurementTelemetry: 'io.inoa.measurement.telemetry'
} as const;
export type CloudEventTypeVO = typeof CloudEventTypeVO[keyof typeof CloudEventTypeVO];

