/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConfigurationDefinitionVO } from "./configurationDefinition";
import { ConfigurationTypeVO } from "./configurationType";

export interface ConfigurationDefinitionStringVO extends ConfigurationDefinitionVO {
	minLength?: number;
	maxLength?: number;
	pattern?: string;
}
export namespace ConfigurationDefinitionStringVO {}
