/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConfigurationDefinitionVO } from './configurationDefinition';


/**
 * Defines a configuration.
 */
export interface ConfigurationVO { 
    definition: ConfigurationDefinitionVO;
    value: object;
}

