/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible types of configuration values.
 */
export type ConfigurationTypeVO = "INTEGER" | "BOOLEAN" | "STRING" | "URL";

export const ConfigurationTypeVO = {
	Integer: "INTEGER" as ConfigurationTypeVO,
	Boolean: "BOOLEAN" as ConfigurationTypeVO,
	String: "STRING" as ConfigurationTypeVO,
	Url: "URL" as ConfigurationTypeVO
};
