/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConfigurationDefinitionVO } from './configurationDefinition';
import { ConfigurationTypeVO } from './configurationType';


export interface ConfigurationDefinitionIntegerVO extends ConfigurationDefinitionVO { 
    minimum?: number;
    maximum?: number;
}
export namespace ConfigurationDefinitionIntegerVO {
}


