/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Possible types of configuration values.
 */
export const ConfigurationTypeVO = {
    Integer: 'INTEGER',
    Boolean: 'BOOLEAN',
    String: 'STRING',
    Url: 'URL'
} as const;
export type ConfigurationTypeVO = typeof ConfigurationTypeVO[keyof typeof ConfigurationTypeVO];

