/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CredentialUpdateVO { 
    /**
     * Name to identify credential.
     */
    name?: string;
    /**
     * Flag if enabled or not.
     */
    enabled?: boolean;
}

