/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Types of supported credentials.
 */
export type CredentialTypeVO = 'psk' | 'rsa';

export const CredentialTypeVO = {
    Psk: 'psk' as CredentialTypeVO,
    Rsa: 'rsa' as CredentialTypeVO
};

