/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Types of supported credentials.
 */
export const CredentialTypeVO = {
    Psk: 'psk',
    Rsa: 'rsa'
} as const;
export type CredentialTypeVO = typeof CredentialTypeVO[keyof typeof CredentialTypeVO];

