/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CredentialTypeVO } from './credentialType';


export interface CredentialCreateVO { 
    /**
     * Name to identify credential.
     */
    name: string;
    /**
     * Flag if enabled or not.
     */
    enabled?: boolean;
    type: CredentialTypeVO;
    /**
     * Value for credential.
     */
    value: Blob;
}
export namespace CredentialCreateVO {
}


