/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Gateway status
 */
export interface GatewayMqttStatusVO { 
    /**
     * connection status
     */
    connected?: boolean;
    /**
     * Common timestamp for created/updated timestamps.
     */
    timestamp?: string;
}

