/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Group to update.
 */
export interface GroupUpdateVO { 
    /**
     * Name of a group.
     */
    name?: string;
}

