/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Group to create.
 */
export interface GroupCreateVO { 
    /**
     * Id as technical reference (never changes).
     */
    group_id?: string;
    /**
     * Name of a group.
     */
    name: string;
}

