/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Log event.
 */
export interface LogEventVO { 
    /**
     * Log tag
     */
    tag: string;
    /**
     * Log level
     */
    level: number;
    /**
     * Log time
     */
    time: number;
    /**
     * Log message
     */
    msg: string;
}

