/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MeasurandTypeVO } from './measurandType';


/**
 * A single measurand that shall be measured.
 */
export interface MeasurandVO { 
    measurand_type: MeasurandTypeVO;
    /**
     * Whether or not this measurand should be measured.
     */
    enabled: boolean;
    /**
     * Interval for measuring this measurand in milliseconds.
     */
    interval: number;
    /**
     * Timeout for measuring this measurand in milliseconds.
     */
    timeout: number;
}

