/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MeasurandTypeVO } from './measurandType';


/**
 * Representation of a measurand belonging to a thing
 */
export interface MeasurandVO { 
    /**
     * URI for the measurand which is unique per gateway
     */
    uri?: string;
    measurand_type: MeasurandTypeVO;
    /**
     * Indicates if the measurand is measured
     */
    enabled: boolean;
    /**
     * Duration between two measurements in milliseconds
     */
    interval: number;
    /**
     * Maximum duration a measurement may take in milliseconds
     */
    timeout: number;
}

