/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of the measurand
 */
export interface MeasurandTypeVO { 
    /**
     * The OBIS code
     */
    obis_id: string;
    /**
     * Name of the measurand type
     */
    name: string;
    /**
     * Description of the measurand type
     */
    description?: string;
}

