/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Technical protocol used to request / transfer measurements.
 */
export type MeasurandProtocolVO = 'JSON_REST_HTTP' | 'MODBUS_RS485' | 'MODBUS_TCP' | 'S0' | 'MBUS' | 'WMBUS';

export const MeasurandProtocolVO = {
    JsonRestHttp: 'JSON_REST_HTTP' as MeasurandProtocolVO,
    ModbusRs485: 'MODBUS_RS485' as MeasurandProtocolVO,
    ModbusTcp: 'MODBUS_TCP' as MeasurandProtocolVO,
    S0: 'S0' as MeasurandProtocolVO,
    Mbus: 'MBUS' as MeasurandProtocolVO,
    Wmbus: 'WMBUS' as MeasurandProtocolVO
};

