/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Technical type of a measurand represented by an OBIS code.
 */
export interface MeasurandTypeVO { 
    /**
     * The OBIS code of the measurand
     */
    obis_code: string;
    /**
     * Human readable name of the type.
     */
    name: string;
    /**
     * Longer description of the type.
     */
    description?: string;
}

