/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MoveGatewayRequestVO { 
    /**
     * Id as tenant reference.
     */
    source_tenant_id: string;
    /**
     * Id as tenant reference.
     */
    target_tenant_id: string;
    /**
     * Id as technical reference (never changes).
     */
    gateway_id: string;
}

