/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PropertyDefinitionVO { 
    /**
     * Name.
     */
    name?: string;
    /**
     * key for the property
     */
    key?: string;
    /**
     * input type for the frontend
     */
    input_type?: PropertyDefinitionVO.InputTypeEnum;
}
export namespace PropertyDefinitionVO {
    export type InputTypeEnum = 'text' | 'number';
    export const InputTypeEnum = {
        Text: 'text' as InputTypeEnum,
        Number: 'number' as InputTypeEnum
    };
}


