/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Remote procedure call command
 */
export interface RpcCommandVO { 
    /**
     * ID of the command
     */
    id?: string;
    /**
     * TODO
     */
    method: string;
    /**
     * Parameters of the command as JSON object
     */
    params?: object;
}

