/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Error response
 */
export interface RpcResponseErrorVO {
	/**
	 * Error code
	 */
	code?: number;
	/**
	 * Error message
	 */
	message?: string;
}
