/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Telemetry payload.
 */
export interface TelemetryRawVO { 
    /**
     * URN with device type and id plus sensor identifier. Sensor can by anything, e.g. obis code or modbus register.
     */
    urn: string;
    /**
     * Timestamp of measurement (epoch milliseconds).
     */
    timestamp: number;
    /**
     * Value of measurement, is a base64 encoded byte array. Will be interpreted later.
     */
    value: string;
    /**
     * Additional stuff describing this measurement.
     */
    ext?: { [key: string]: string; };
}

