/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Representation of a tenant.
 */
export interface TenantVO {
	/**
	 * Id as tenant reference.
	 */
	tenant_id: string;
	/**
	 * Name of a tenant.
	 */
	name: string;
	/**
	 * Is tenant enabled
	 */
	enabled: boolean;
	/**
	 * Regular expression to force specific gateway IDs for this tenant
	 */
	gateway_id_pattern: string;
	/**
	 * Common timestamp for created/updated timestamps.
	 */
	created: string;
	/**
	 * Common timestamp for created/updated timestamps.
	 */
	updated: string;
	/**
	 * Common timestamp for created/updated timestamps.
	 */
	deleted?: string;
}
