/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Group to update.
 */
export interface TenantUpdateVO {
	/**
	 * Name of a tenant.
	 */
	name?: string;
	/**
	 * Is tenant enabled
	 */
	enabled?: boolean;
	/**
	 * Regular expression to force specific gateway IDs for this tenant
	 */
	gateway_id_pattern?: string;
}
