/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ThingTypeCategoryVO } from './thingTypeCategory';
import { ThingConfigurationVO } from './thingConfiguration';
import { ThingTypeProtocolVO } from './thingTypeProtocol';


/**
 * Representation of a type / class of things to be updated.
 */
export interface ThingTypeUpdateVO { 
    /**
     * Human readable name.
     */
    name: string;
    category?: ThingTypeCategoryVO;
    /**
     * Additional description of the thing type
     */
    description?: string;
    /**
     * An optional version of the thing type (e.g. firmware, revision, ...)
     */
    version?: string;
    protocol: ThingTypeProtocolVO;
    /**
     * List of measurands this type of thing supports
     */
    measurands?: Array<string>;
    /**
     * List of settings that can be configured for things of this type
     */
    configurations?: Array<ThingConfigurationVO>;
}
export namespace ThingTypeUpdateVO {
}


