/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PropertyVO } from './property';


/**
 * Thing channel to create.
 */
export interface ThingChannelVO { 
    /**
     * key for the channel
     */
    key: string;
    properties?: Array<PropertyVO>;
}

