/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ThingConfigurationVO } from './thingConfiguration';
import { MeasurandTypeVO } from './measurandType';


/**
 * Representation of a type / class of things.
 */
export interface ThingTypeUpdateVO { 
    /**
     * Id as technical reference (never changes).
     */
    identifier?: string;
    /**
     * Human readable name.
     */
    name?: string;
    /**
     * Category for logical grouping.
     */
    category?: string;
    /**
     * Additional description of the thing type
     */
    description?: string;
    /**
     * An optional version of the thing type (e.g. firmware, revision, ...)
     */
    version?: string;
    /**
     * The protocol the thing type uses. If a thing supports several protocols, one may define several thing types.
     */
    protocol?: ThingTypeUpdateVO.ProtocolEnum;
    /**
     * List of measurands this type of thing supports
     */
    measurands?: Array<MeasurandTypeVO>;
    /**
     * List of settings that can be configured for things of this type
     */
    configurations?: Array<ThingConfigurationVO>;
}
export namespace ThingTypeUpdateVO {
    export type ProtocolEnum = 'JSON_REST_HTTP' | 'MODBUS_RS458' | 'MODBUS_TCP' | 'S0' | 'MBUS' | 'WMBUS';
    export const ProtocolEnum = {
        JsonRestHttp: 'JSON_REST_HTTP' as ProtocolEnum,
        ModbusRs458: 'MODBUS_RS458' as ProtocolEnum,
        ModbusTcp: 'MODBUS_TCP' as ProtocolEnum,
        S0: 'S0' as ProtocolEnum,
        Mbus: 'MBUS' as ProtocolEnum,
        Wmbus: 'WMBUS' as ProtocolEnum
    };
}


