/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ThingVO } from './thing';


/**
 * Page for thing types.
 */
export interface ThingPageVO { 
    /**
     * List of entries on page.
     */
    content: Array<ThingVO>;
    /**
     * Total available entries.
     */
    total_size: number;
}

