/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A single configuration definition of a thing
 */
export interface ThingConfigurationVO { 
    /**
     * Name of the configuration
     */
    name: string;
    /**
     * An optional description of the configuration
     */
    description?: string;
    /**
     * The type of the configuration
     */
    type: ThingConfigurationVO.TypeEnum;
    /**
     * An optional regular expression validating the configuration value
     */
    validation_regex?: string;
}
export namespace ThingConfigurationVO {
    export type TypeEnum = 'STRING' | 'NUMBER' | 'BOOLEAN';
    export const TypeEnum = {
        String: 'STRING' as TypeEnum,
        Number: 'NUMBER' as TypeEnum,
        Boolean: 'BOOLEAN' as TypeEnum
    };
}


