/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Category for logical grouping.
 */
export type ThingTypeCategoryVO = 'NONE' | 'ELECTRIC_METER' | 'GAS_METER' | 'CURRENT_TRANSFORMER' | 'SMART_PLUG';

export const ThingTypeCategoryVO = {
    None: 'NONE' as ThingTypeCategoryVO,
    ElectricMeter: 'ELECTRIC_METER' as ThingTypeCategoryVO,
    GasMeter: 'GAS_METER' as ThingTypeCategoryVO,
    CurrentTransformer: 'CURRENT_TRANSFORMER' as ThingTypeCategoryVO,
    SmartPlug: 'SMART_PLUG' as ThingTypeCategoryVO
};

