/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The protocol the thing type uses. If a thing supports several protocols, one may define several thing types.
 */
export const ThingTypeProtocolVO = {
    JsonRestHttp: 'JSON_REST_HTTP',
    ModbusRs458: 'MODBUS_RS458',
    ModbusTcp: 'MODBUS_TCP',
    S0: 'S0',
    Mbus: 'MBUS',
    Wmbus: 'WMBUS',
    Adc: 'ADC',
    Rms: 'RMS'
} as const;
export type ThingTypeProtocolVO = typeof ThingTypeProtocolVO[keyof typeof ThingTypeProtocolVO];

