/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ThingConfigurationsInnerVO } from './thingConfigurationsInner';
import { MeasurandVO } from './measurand';


/**
 * Thing with fields.
 */
export interface ThingUpdateVO { 
    /**
     * Human readable name.
     */
    name?: string;
    /**
     * Long description of the thing
     */
    description?: any | null;
    /**
     * Id as technical reference (never changes).
     */
    gateway_id?: string;
    /**
     * Id as technical reference (never changes).
     */
    thing_type_id?: string;
    /**
     * List of measurands and its configuration
     */
    measurands?: Array<MeasurandVO>;
    /**
     * List of thing configurations
     */
    configurations?: Array<ThingConfigurationsInnerVO>;
}

