/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MeasurandProtocolVO } from './measurandProtocol';
import { ThingConfigurationVO } from './thingConfiguration';
import { MeasurandTypeVO } from './measurandType';


/**
 * Representation of a specific thing family. For example a type of electrical meter.
 */
export interface ThingTypeVO { 
    /**
     * Id as technical reference (never changes).
     */
    id?: string;
    /**
     * Name.
     */
    name?: string;
    /**
     * Category.
     */
    category?: string;
    /**
     * Longer description of a thing type.
     */
    description?: string;
    /**
     * Physical version or firmware version of the thing type
     */
    version?: string;
    /**
     * List of measurands this type of thing offers.
     */
    measurand_types?: Array<MeasurandTypeVO>;
    /**
     * List of configuration settings this type of thing needs.
     */
    configurations?: Array<ThingConfigurationVO>;
    protocol?: MeasurandProtocolVO;
}
export namespace ThingTypeVO {
}


