/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MeasurandVO } from './measurand';


/**
 * Thing with fields.
 */
export interface ThingVO { 
    /**
     * Id as technical reference (never changes).
     */
    id: string;
    /**
     * Human readable name.
     */
    name: string;
    /**
     * Long description of the thing
     */
    description?: string;
    /**
     * Id as technical reference (never changes).
     */
    gateway_id: string;
    /**
     * Id as technical reference (never changes).
     */
    thing_type_id: string;
    /**
     * List of measurands and its configuration
     */
    measurands?: Array<MeasurandVO>;
    /**
     * Key / value map of thing configurations
     */
    configurations?: { [key: string]: string; };
}

