/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PropertyDefinitionVO } from './propertyDefinition';
import { ThingTypeChannelVO } from './thingTypeChannel';


/**
 * User with fields.
 */
export interface ThingTypeVO { 
    /**
     * Id as technical reference (never changes).
     */
    id: string;
    /**
     * Name.
     */
    name: string;
    /**
     * json_schema
     */
    json_schema?: { [key: string]: any; };
    /**
     * ui_layout
     */
    ui_layout?: Array<{ [key: string]: any; }>;
    properties?: Array<PropertyDefinitionVO>;
    channels?: Array<ThingTypeChannelVO>;
    /**
     * Common timestamp for created/updated timestamps.
     */
    created: string;
    /**
     * Common timestamp for created/updated timestamps.
     */
    updated: string;
}

