/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Possible data types of a thing configuration.
 */
export type ThingConfigurationTypeVO = 'STRING' | 'NUMBER' | 'BOOLEAN';

export const ThingConfigurationTypeVO = {
    String: 'STRING' as ThingConfigurationTypeVO,
    Number: 'NUMBER' as ThingConfigurationTypeVO,
    Boolean: 'BOOLEAN' as ThingConfigurationTypeVO
};

