/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ThingConfigurationVO } from './thingConfiguration';


export interface ThingConfigurationsInnerVO { 
    configuration: ThingConfigurationVO;
    /**
     * Value of the configuration
     */
    value: string;
}

