/**
 * Inoa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Category for logical grouping.
 */
export const ThingTypeCategoryVO = {
    None: 'NONE',
    ElectricMeter: 'ELECTRIC_METER',
    GasMeter: 'GAS_METER',
    CurrentTransformer: 'CURRENT_TRANSFORMER',
    SmartPlug: 'SMART_PLUG'
} as const;
export type ThingTypeCategoryVO = typeof ThingTypeCategoryVO[keyof typeof ThingTypeCategoryVO];

