/**
 * Inoa Fleet API
 * Definitions for Inoa Fleet.
 *
 * The version of the OpenAPI document: ${project.version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ThingConfigurationTypeVO } from './thingConfigurationType';


/**
 * Configuration of a thing. For example baud rate, bus address, serial, ...
 */
export interface ThingConfigurationVO { 
    /**
     * Property name of the configuration setting.
     */
    name: string;
    /**
     * Description of the configuration setting.
     */
    description?: string;
    type: ThingConfigurationTypeVO;
    /**
     * Regex to validation the configuration value.
     */
    validation_regex?: string;
    /**
     * The value of the configuration setting.
     */
    value: string;
}
export namespace ThingConfigurationVO {
}


