commonLabels:
  app.kubernetes.io/name: measurement

resources:
  - deployment.yaml

configMapGenerator:
  - name: measurement-environment
    literals:
      - ENDPOINTS_ALL_PORT=8090
      - KAFKA_BOOTSTRAP_SERVERS=kafka.infrastructure:9092
      - KAFKA_CONSUMERS_DEFAULT_METADATA_MAX_AGE_MS=1000
      - INFLUXDB_URL=http://influxdb.infrastructure
      - INFLUXDB_ORGANISATION=inoa
      - INFLUXDB_BUCKET=default
      - MICRONAUT_ENVIRONMENTS=postgres
      - MICRONAUT_SECURITY_TOKEN_JWT_SIGNATURES_JWKS_KEYCLOAK_URL=http://keycloak.infrastructure/realms/inoa/protocol/openid-connect/certs
      - DATASOURCES_DEFAULT_HOST=postgres.infrastructure
      - DATASOURCES_DEFAULT_DATABASE=measurement
      - DATASOURCES_DEFAULT_USERNAME=measurement
      - INOA_FLEET_REGISTRY_SECURITY_TENANT_AUDIENCE_WHITELIST=inoa-measurement

secretGenerator:
  - name: measurement-environment
    literals: [INFLUXDB_TOKEN=changeMe, DATASOURCES_DEFAULT_PASSWORD=changeMe]