# https://yarnpkg.com/configuration/yarnrc
nodeLinker: node-modules

# Yarn will not execute the postinstall scripts from third-party packages when installing the project.
enableScripts: false

# Define whether anonymous telemetry data should be sent or not.
enableTelemetry: false

# use local npm mirror
npmRegistryServer: https://nexus.grayc.io/repository/npmjs.org/
