apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-admin-ui
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fleet-admin-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fleet-admin-ui
    spec:
      containers:
        - name: fleet-admin-ui
          image: ghcr.io/inoa-io/fleet-admin-ui
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: inoa-environment
                optional: true
            - configMapRef:
                name: fleet-admin-ui-environment
            - secretRef:
                name: fleet-admin-ui-environment
          ports:
            - name: http
              containerPort: 8080
            - name: managment
              containerPort: 8090
          startupProbe:
            httpGet:
              path: /endpoints/health
              port: managment
            initialDelaySeconds: 10
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 120
          readinessProbe:
            httpGet:
              path: /endpoints/health/readiness
              port: managment
          livenessProbe:
            httpGet:
              path: /endpoints/health/liveness
              port: managment
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            readOnlyRootFilesystem: false
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 5
