apiVersion: v1
kind: Service
metadata:
  name: fleet-mqtt-broker
spec:
  type: LoadBalancer
  ports:
    - name: mqtt
      port: 8883
      targetPort: mqtt
  selector:
    app.kubernetes.io/name: fleet-mqtt-broker
