apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: influxdb
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  location: europe-west3-c
  resourceID: inoa-dev-influxdb
  size: 5
  type: pd-standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: inoa-dev-influxdb
spec:
  gcePersistentDisk:
    pdName: inoa-dev-influxdb
    fsType: ext4
  storageClassName: standard
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
spec:
  volumeName: inoa-dev-influxdb
  storageClassName: standard
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
