apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
spec:
  config:
    analytics:
      check_for_plugin_updates: "false"
      check_for_updates: "false"
      enable_feedback_links: "false"
      reporting_enabled: "false"
    auth:
      disable_login_form: "false"
    auth.oauth:
      auto_login: "false"
    auth.generic_oauth:
      allow_sign_up: "false"
      api_url: https://auth.${inoa_domain}/realms/inoa/protocol/openid-connect/userinfo
      auth_url: https://auth.${inoa_domain}/realms/inoa/protocol/openid-connect/auth
      client_id: grafana
      enabled: "true"
      name: keycloak
      scopes: openid
      token_url: https://auth.${inoa_domain}/realms/inoa/protocol/openid-connect/token
    database:
      host: postgres
      type: postgres
      name: grafana
    log:
      level: info
    help:
      enabled: "true"
    metrics:
      enabled: "true"
    plugins:
      plugin_admin_enabled: "true"
    security:
      content_security_policy: "false"
      cookie_samesite: lax
      cookie_secure: "false"
      disable_gravatar: "true"
      disable_initial_admin_creation: "true"
      strict_transport_security: "true"
    server:
      enable_gzip: "false"
      enforce_domain: "false"
      http_port: "3000"
      root_url: https://grafana.${inoa_domain}
      router_logging: "false"
    unified_alerting:
      enabled: "false"
    users:
      allow_sign_up: "false"
      auto_assign_org_role: Admin
  deployment:
    spec:
      replicas: 1
      template:
        spec:
          initContainers:
            - name: wait-for-postgres
              image: docker.io/library/postgres:17.6
              command:
                - sh
                - -c
                - |
                  until echo "$(date '+%T') connect psql ..." && psql && echo "$(date '+%T') ... connected"; do sleep 0.1; done
              env:
                - name: PGCONNECT_TIMEOUT
                  value: "1"
                - name: PGHOST
                  valueFrom:
                    secretKeyRef:
                      name: grafana-env
                      key: GF_DATABASE_HOST
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: grafana-env
                      key: GF_DATABASE_USER
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-env
                      key: GF_DATABASE_PASSWORD
          containers:
            - name: grafana
              image: grafana/grafana
              envFrom:
                - secretRef:
                    name: grafana-env
              ports:
                - name: grafana-http
                  containerPort: 3000
              startupProbe:
                httpGet:
                  path: /api/health
                  port: grafana-http
                failureThreshold: 60
                periodSeconds: 2
                initialDelaySeconds: 5
                timeoutSeconds: 2
              readinessProbe:
                httpGet:
                  path: /api/health
                  port: grafana-http
                failureThreshold: 5
                periodSeconds: 10
                initialDelaySeconds: 10
              resources:
                requests:
                  memory: 256Mi
                  cpu: 100m
                limits:
                  memory: 512Mi
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
          volumes:
            - name: tmp
              emptyDir:
                sizeLimit: 512Mi
  service:
    spec:
      type: ClusterIP
      ports:
        - name: http
          port: 80
          targetPort: grafana-http
  ingress:
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
        traefik.ingress.kubernetes.io/router.tls: "true"
    spec:
      ingressClassName: traefik
      rules:
        - host: grafana.${inoa_domain}
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: grafana-service
                    port:
                      number: 80
      tls:
        - hosts:
            - grafana.${inoa_domain}
          secretName: grafana-tls
