labels:
  - pairs:
      app.kubernetes.io/name: kafka
      app.kubernetes.io/technology: java

resources:
  - pdb.yaml
  - service.yaml
  - statefulset.yaml

replacements:
  - source:
      kind: StatefulSet
      fieldPath: spec.replicas
    targets:
      - select:
          kind: StatefulSet
        fieldPaths:
          - spec.template.spec.initContainers.[name=kafka-init-properties].env.[name=KAFKA_REPLICAS].value
  - source:
      kind: StatefulSet
      fieldPath: spec.serviceName
    targets:
      - select:
          kind: StatefulSet
        fieldPaths:
          - spec.template.spec.initContainers.[name=kafka-init-properties].env.[name=KAFKA_CONTROLLER_SERVICE].value
