apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: kafka-0
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  location: europe-west3-c
  resourceID: <patched>-kafka-0
  size: 1
  type: pd-standard
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: kafka-1
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  location: europe-west3-c
  resourceID: <patched>-kafka-1
  size: 1
  type: pd-standard
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: kafka-2
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  location: europe-west3-c
  resourceID: <patched>-kafka-2
  size: 1
  type: pd-standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-0
spec:
  gcePersistentDisk:
    pdName: <patched>-kafka-0
    fsType: ext4
  storageClassName: standard
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-1
spec:
  gcePersistentDisk:
    pdName: <patched>-kafka-1
    fsType: ext4
  storageClassName: standard
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-2
spec:
  gcePersistentDisk:
    pdName: <patched>-kafka-2
    fsType: ext4
  storageClassName: standard
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-kafka-0
spec:
  volumeName: kafka-0
  storageClassName: standard
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-kafka-1
spec:
  volumeName: kafka-1
  storageClassName: standard
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-kafka-2
spec:
  volumeName: kafka-2
  storageClassName: standard
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
