apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    labels:
        app: postgres
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:hxeH/U9pR+4=,iv:qLPsQLvKOuHo8JG/NR5HPaGHXfV6LSI7o1QfJENU0ig=,tag:myjSoGKE9OINeF58f1fWZA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:lPpx8wjAjsig39U4o5XZsLsWsabeLA==,iv:MworWB3O7ZCgpjstxHxXIjidLO9Uef40aEtQxODGkY0=,tag:ejDvI2AKyIN0q/iUDklTIw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/grayc-infrastructure/locations/europe/keyRings/sops/cryptoKeys/fluxcd
          created_at: "2025-03-24T15:13:12Z"
          enc: CiQAIt230CL3rvBFYpHyyjbo/yQlR0hRTjt8bC7KpF+g+DBFvZcSSQD2lEBUeMMOYN2u57lEJiWyiSp+5x6qLdIv/7OxvSkWcOGRI5ybhScnlOeb4G9W0jpMmJwRU54HPgF3dr/oTqHPuGbNRn8mzzQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-31T08:43:37Z"
    mac: ENC[AES256_GCM,data:8tc0hGS+TV/J837MQWHcvMRPNnmrVE6kJ1hlELTir3MlsICFHuXPmBtbc0eu5cE/xL/1hbE0fFMxqxY6qpBoVrh725CGbgrPCwtpGy762qRP2Sx1KYlvuYsOotVKFeBv7PpNBgshceswdyJGMgy2FiIyXVhJ94o5CuVZ850+n6Q=,iv:0+9jAD3Tv4B/mutkqzcBwf0gu4vuaoHRbij/qWRg4Gc=,tag:c57nyuPYuODCdUY39MwfWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
