apiVersion: v1
kind: Secret
metadata:
    name: postgres-env
    labels:
        app: postgres
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:hxeH/U9pR+4=,iv:qLPsQLvKOuHo8JG/NR5HPaGHXfV6LSI7o1QfJENU0ig=,tag:myjSoGKE9OINeF58f1fWZA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:lPpx8wjAjsig39U4o5XZsLsWsabeLA==,iv:MworWB3O7ZCgpjstxHxXIjidLO9Uef40aEtQxODGkY0=,tag:ejDvI2AKyIN0q/iUDklTIw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/grayc-infrastructure/locations/europe/keyRings/sops/cryptoKeys/fluxcd
          created_at: "2025-03-24T15:13:12Z"
          enc: CiQAIt230CL3rvBFYpHyyjbo/yQlR0hRTjt8bC7KpF+g+DBFvZcSSQD2lEBUeMMOYN2u57lEJiWyiSp+5x6qLdIv/7OxvSkWcOGRI5ybhScnlOeb4G9W0jpMmJwRU54HPgF3dr/oTqHPuGbNRn8mzzQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-31T08:55:27Z"
    mac: ENC[AES256_GCM,data:1rUKflYKeRLIxJJH5IoHn0c6uCgeYicJu65w/VloAbcB4ito0mMHNj2bY80gGGQBQnFUgNsDkTjJLZhkHH1ER81UTupQ66q0U3gCvHDkJ6l9AF+O4JzNlo/zMmUU1wSeAZb83dwAmG/Gmu1cWwQSHKQB9kDUHkEOTbSxlRWyHYQ=,iv:5GELSKl4R6NUozMIFMvFHoeavZY6JVYU9AsYraESe9g=,tag:prfpMvRz1NFvX/TY+f8gRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
