apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    labels:
        app: postgres
type: Opaque
data:
    POSTGRES_USER: ENC[AES256_GCM,data:G95S5vzXjlY=,iv:Hprn1XsPn98AL8LbF4bB88ZYTTtAyzJ9AzCM8NLjFQQ=,tag:15KibFS//Ltwv3uLc3UjsA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0d50hxEopvKlG9hJksbjcAKVNvXX1g==,iv:jg6m/QUpuXnSocm+Xia/+VpGhmHKpaJGyg6iFnLMzzQ=,tag:5lhBHFwbmAztvJnMoOTkbQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/grayc-infrastructure/locations/europe/keyRings/sops/cryptoKeys/fluxcd
          created_at: "2025-03-24T15:13:12Z"
          enc: CiQAIt230CL3rvBFYpHyyjbo/yQlR0hRTjt8bC7KpF+g+DBFvZcSSQD2lEBUeMMOYN2u57lEJiWyiSp+5x6qLdIv/7OxvSkWcOGRI5ybhScnlOeb4G9W0jpMmJwRU54HPgF3dr/oTqHPuGbNRn8mzzQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-24T15:13:12Z"
    mac: ENC[AES256_GCM,data:zbo7n7yZofFIaO9ieMgGKFEfsNzfwX5vAA/BxbcwmB3Un6gz047H28yVgPdakQOIB4dJQ+x26puQY+6C2SMPDrP8Mh/XjTwiUJWd7/Z25xcXhKvI5yBwf0suv9gqcP+iVAaLC/VW2EuR2B/y3D5sNG73u0QIgOi0oP+ReN0jhms=,iv:bTh0+KD/l10WxI065tLDUIUDKSvvSy3OCJSDiDMvoV0=,tag:Q2p9PZZraD1k8GUC3vVWoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
