micronaut:
  application:
    name: ${project.artifactId}
    version: ${project.version}

## see https://docs.micronaut.io/latest/guide/index.html#providedEndpoints
endpoints:
  all:
    path: /endpoints
    sensitive: false
  health:
    details-visible: ANONYMOUS
  caches:
    enabled: true
