apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inoa-keycloak
  namespace: inoa
  title: INOA Keycloak
  description: The authorization service in context of INOA.
  annotations:
    backstage.io/techdocs-entity: system:inoa/inoa-cloud
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=inoa
    simpleicons.org/icon-slug: keycloak
spec:
  owner: default/grayc
  system: inoa/inoa-cloud
  lifecycle: productive
  type: service
  dependsOn:
    - component:inoa-postgres
