apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inoa-groundcontrol
  title: INOA Ground Control
  description:
    Ground Control is the user interface of INOA cloud that offers featrues to manage a fleet of IoT gatways.
  annotations:
    backstage.io/source-location: url:https://git.grayc.io/inoa/cloud/app
    backstage.io/techdocs-ref: dir:../techdocs
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=inoa
spec:
  owner: grayc
  system: default/inoa
  lifecycle: productive
  type: website
  dependsOn:
    - component:inoa-fleet
