apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inoa-groundcontrol
  namespace: inoa
  title: INOA Ground Control
  description: Ground Control is the user interface of INOA cloud that offers featrues to manage a fleet of IoT gatways.
  annotations:
    backstage.io/source-location: url:https://git.grayc.io/inoa/cloud/src/branch/main/app
    backstage.io/techdocs-entity: system:inoa/inoa-cloud
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=inoa
spec:
  owner: default/grayc
  system: inoa/inoa-cloud
  lifecycle: productive
  type: website
  dependsOn:
    - component:inoa-fleet
