apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: keycloak-realm-inoa
  title: Keycloak Realm INOA
  links:
    - title: Admin Console
      url: https://oidc.inoa.io/admin/inoa/console
  annotations:
    backstage.io/kubernetes-namespace: infrastructure
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=keycloak
spec:
  owner: grayc
  system: default/inoa-cloud
  lifecycle: production
  type: keycloak-realm
  dependsOn:
    - component:keycloak
