# creation rules are evaluated sequentially, the first match wins
creation_rules:

  # encrypt all in directory for secrets
  - path_regex: ^.*/secrets/.*$
    gcp_kms: projects/grayc-infrastructure/locations/europe/keyRings/sops/cryptoKeys/fluxcd
