namespace: inoa-dev

commonLabels:
  app.kubernetes.io/part-of: inoa
  app.kubernetes.io/env: dev

images:
  - name: docker.io/library/influxdb
    newTag: 2.7.5
  - name: docker.io/obsidiandynamics/kafdrop
    newTag: 4.0.1
  - name: docker.io/provectuslabs/kafka-ui
    newTag: v0.7.1
  - name: docker.io/redpandadata/console
    newTag: v2.4.3
  - name: ghcr.io/grayc-de/kafka
    newTag: 3.6.1
  - name: ghcr.io/inoa-io/inoa
    newTag: snapshot

resources:
  - ../../base/fluxcd
  - influxdb
  - kafka
  - kafka-console
  - kafka-ui
  - kafdrop
  - inoa
