apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mcnoize
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: mcnoize
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10
  template:
    metadata:
      annotations:
        fluentbit.io/exclude: "true"
      labels:
        app.kubernetes.io/name: mcnoize
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-ghcr-io
      containers:
        - name: mcnoize
          image: ghcr.io/inoa-io/mcnoize:0.0.2
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: mcnoize-env
          env:
            - name: MCNOIZE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              memory: 5Mi
            requests:
              cpu: 1m
              memory: 5Mi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
      automountServiceAccountToken: false
      enableServiceLinks: false
      terminationGracePeriodSeconds: 1
