apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: inoa-mqtt-tls
spec:
  dnsNames: [mqtt.<patched>.inoa.io]
  secretName: inoa-mqtt-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
