apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: fleet
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  resourceID: inoa-<patched>-fleet
  instanceRef:
    namespace: infrastructure
    name: postgres
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: fleet
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  resourceID: inoa-<patched>-fleet
  instanceRef:
    namespace: infrastructure
    name: postgres
  password:
    valueFrom:
      secretKeyRef:
        name: fleet-env
        key: DATASOURCES_DEFAULT_PASSWORD
