openapi: 3.0.3
info:
  title: Hono Message Definitions
  version: 0.1.0
  description: |
    Model definitions for messages over Hono.
  license:
    name: Apache License 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  contact:
    name: GrayC GmbH
    url: https://grayc.de
paths: {}
components:
  schemas:

    HonoTelemetryMessage:
      description: 'Telemetry payload.'
      type: object
      properties:
        urn:
          description: 'URN with device type and id plus sensor identifier. Sensor can by anything, e.g. obis code or modbus register.'
          type: string
          pattern: 'urn:(?<deviceType>[a-zA-Z0-9\-]{2,32}):(?<deviceId>[a-zA-Z0-9\-]{2,36}):(?<sensor>[a-zA-Z0-9_\-\:*]{2,64})'
          example: 'urn:dvh4013:12314214:1-0:1.8.0*255'
        timestamp:
          description: 'Timestamp of measurement (epoch milliseconds).'
          type: integer
          format: int64
          example: 1234567890
        value:
          description: 'Value of measurement, is a base64 encoded byte array. Will be interpreted later.'
          type: string
          format: byte
          example: MDgxNQ==
        ext:
          description: 'Additional stuff describing this measurement.'
          type: string
          maxLength: 16
          additionalProperties:
            type: string
            maxLength: 32
          example:
            obis: power_in
      required:
        - urn
        - timestamp
        - value
      example:
        urn: 'urn:dvh4013:12314214:1-0:1.8.0*255'
        timestamp: 1631170019
        value: MDgxNQ==
        ext:
          obis: power_in
