openapi: 3.0.3
info:
  title: INOA Message Definitions
  version: 0.1.0
  description: |
    Model definitions for messages produced by INOA cloud.
  license:
    name: Apache License 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  contact:
    name: GrayC GmbH
    url: https://grayc.de
paths: {}
components:
  schemas:

    InoaTelemetryMessage:
      description: 'Inoa payload.'
      type: object
      properties:
        tenant_id:
          description: 'Id of tenant.'
          type: string
          format: uuid
          example: 10001
        gateway_id:
          description: 'Id of gateway @ tenant.'
          type: string
          format: uuid
          example: 10001
        urn:
          description: 'TODO'
          type: string
          pattern: 'urn:(?<deviceType>[a-zA-Z0-9\-]{2,32}):(?<deviceId>[a-zA-Z0-9\-]{2,36}):(?<sensor>[a-zA-Z0-9\-\:*]{2,64})'
          example: 'urn:dvh4013:12314214:1-0:1.8.0*255'
        device_type:
          description: 'TODO'
          type: string
          pattern: '[a-zA-Z0-9\-]{2,32}'
          example: 'dvh4013'
        device_id:
          description: 'TODO'
          type: string
          pattern: '[a-zA-Z0-9\-]{2,36}'
          example: '12314214'
        sensor:
          description: 'TODO'
          type: string
          pattern: '[a-zA-Z0-9\-\:*]{2,64}'
          example: '1-0:1.8.0*255'
        timestamp:
          description: 'Timestamp of measurement value.'
          type: string
          format: date-time
          example: '2021-09-09T06:46:59'
        value:
          description: 'Value of measurement.'
          type: number
          format: double
          example: 99.42
        ext:
          description: 'Additional stuff describing this measurement.'
          type: string
          maxLength: 100
          additionalProperties:
            type: string
            maxLength: 100
          example:
            obis-1: 0815
      required:
        - tenant_id
        - gateway_id
        - urn
        - device_type
        - device_id
        - sensor
        - timestamp
        - value
      example:
        tenant_id: 123
        gateway_id: 345
        urn: 'urn:dvh4013:12314214:1-0:1.8.0*255'
        device_type: dvh4013
        device_id: 12314214
        sensor: 1-0:1.8.0*255
        timestamp: 2021-09-09T06:46:59
        value: 99.42
        metadata:
          obis: '1-0:1.8.0*255'
