commonLabels:
  app.kubernetes.io/name: kafka

resources:
  - ../../../base/kafka
  - pvc.yaml

patches:
  - target:
      kind: StatefulSet
    patch: |-
      - op: test
        path: /spec/template/spec/initContainers/1/env/0/name
        value: KAFKA_CLUSTER_ID
      - op: replace
        path: /spec/template/spec/initContainers/1/env/0/value
        value: ZGI1NTk0YmY3NzVjNDk5MD
