apiVersion: v1
kind: Service
metadata:
  name: fleet
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: mqtt
      port: 1883
      targetPort: mqtt
    - name: mqtts
      port: 8883
      targetPort: mqtts
  selector:
    app.kubernetes.io/name: fleet
