export * from './auth.service';
import { AuthService } from './auth.service';
export * from './configuration.service';
import { ConfigurationService } from './configuration.service';
export * from './credentials.service';
import { CredentialsService } from './credentials.service';
export * from './gateway.service';
import { GatewayService } from './gateway.service';
export * from './gateways.service';
import { GatewaysService } from './gateways.service';
export * from './groups.service';
import { GroupsService } from './groups.service';
export * from './properties.service';
import { PropertiesService } from './properties.service';
export * from './remote.service';
import { RemoteService } from './remote.service';
export * from './tenants.service';
import { TenantsService } from './tenants.service';
export * from './thingTypes.service';
import { ThingTypesService } from './thingTypes.service';
export * from './things.service';
import { ThingsService } from './things.service';
export const APIS = [AuthService, ConfigurationService, CredentialsService, GatewayService, GatewaysService, GroupsService, PropertiesService, RemoteService, TenantsService, ThingTypesService, ThingsService];
