micronaut:
  application:
    name: ${project.artifactId}
    version: ${project.version}

  ## see https://docs.micronaut.io/latest/guide/index.html#staticResources
  router:
    static-resources:
      openapi:
        paths: classpath:openapi
        mapping: /openapi/**

  ## see https://docs.micronaut.io/latest/guide/index.html#cors
  server:
    cors:
      enabled: true
      default:
        allowedMethods:
          - GET
          - PATCH
          - POST
          - PUT
          - DELETE
          - FETCH
          - OPTIONS
  netty:
    event-loops:
      other:
        num-threads: 10
        prefer-native-transport: true

  http:
    client:
      read-timeout: 30s
      event-loop-group: other

  security:
    ## see https://micronaut-projects.github.io/micronaut-security/latest/guide/#interceptUrlMap
    intercept-url-map:
      - pattern: /endpoints/**
        access: isAnonymous()
      - pattern: /openapi/**
        access: isAnonymous()
      - pattern: /gateway
        access: isAnonymous()
        http-method: POST
      - pattern: /**
        access: isAuthenticated()
    token:
      jwt:
        claims-validators:
          not-before: false

  # see https://micronaut-projects.github.io/micronaut-data/latest/guide/configurationreference.html
  data:
    pageable:
      max-page-size: 1000
      default-page-size: 25


## see https://docs.micronaut.io/latest/guide/index.html#providedEndpoints
endpoints:
  all:
    path: /endpoints
    sensitive: false
  health:
    details-visible: ANONYMOUS
  loggers:
    write-sensitive: false

## see https://docs.micronaut.io/latest/guide/index.html#jsonBinding
jackson:
  bean-introspection-module: true
  always-serialize-errors-as-list: false
  serialization:
    writeDatesAsTimestamps: false

## see https://micronaut-projects.github.io/micronaut-sql/latest/guide/#jdbc
datasources:
  default:
    url: jdbc:h2:mem:${datasources.default.database};MODE=PostgreSQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    database: registry
    username: registry
    password: changeMe
    dialect: POSTGRES

## see https://micronaut-projects.github.io/micronaut-flyway/latest/guide/index.html#additionalConfig
flyway:
  datasources:
    default:
      locations: classpath:database
