commonLabels:
  app.kubernetes.io/name: fleet

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: fleet-environment
    literals:
      - ENDPOINTS_ALL_PORT=8090
      - MICRONAUT_ENVIRONMENTS=postgres
      - MICRONAUT_SECURITY_TOKEN_JWT_SIGNATURES_JWKS_KEYCLOAK_URL=http://keycloak.infrastructure/realms/inoa/protocol/openid-connect/certs
      - DATASOURCES_DEFAULT_HOST=postgres.infrastructure
      - DATASOURCES_DEFAULT_DATABASE=fleet
      - DATASOURCES_DEFAULT_USERNAME=fleet
      - INOA_FLEET_REGISTRY_SECURITY_TENANT_AUDIENCE_WHITELIST=inoa-fleet

secretGenerator:
  - name: fleet-environment
    literals: [DATASOURCES_DEFAULT_PASSWORD=changeMe]
