resources:
  - ../../../base/influxdb
  - secrets.yaml

images:
  - name: docker.io/library/influxdb:<patched>
    newTag: 2.8.0@sha256:9e967a2283f54ecd401377f1ed677c882adc23dd4090fb5f0c7ebe98a8138a8a
