resources:
  - ../../../base/influxdb
  - secrets.yaml

images:
  - name: docker.io/library/influxdb:<patched>
    newTag: 2.8.0@sha256:38829bd08b47bbfb23ee8ef98fef45ac59abb78d4d7e451870b7499840e0f365
