apiVersion: v1
kind: Secret
metadata:
  name: influxdb-env
  labels:
    app: influxdb
type: Opaque
stringData:
  DOCKER_INFLUXDB_INIT_USERNAME: ENC[AES256_GCM,data:WApBU8E=,iv:Hu8Ler+LH9LrWUlh1aMdR3Lacizogy+4nQ6BzjHw614=,tag:tAGHA0Goa/2Wyql5nCX39w==,type:str]
  DOCKER_INFLUXDB_INIT_PASSWORD: ENC[AES256_GCM,data:cejiYQDkqh1aWlracuUpYEsxqqD1zA==,iv:Kh1u65U9wtqBmr/YORgWClJYwMtNsa3YozZFxvF6S5Q=,tag:5+pxi3Yj8KMCUUuLe2ke7w==,type:str]
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ENC[AES256_GCM,data:Q44wpT64oGgBPEWudbtQvYLVK/i5Sj0ptmz4OuV1W/TAYSuK0wJxvy7NH/2cwfMpN1Kjig6Me5VWhT3l27hPCto4tpoXShoSiq9HnkRzuvx4fvJoyZugVw==,iv:bs6rXGvg1W5o9YnWdGBzLPFjEkugVtIM2nWARzmQ/j0=,tag:MMMXN4FAINeqqL06gsi5sQ==,type:str]
sops:
  kms: []
  gcp_kms:
    - resource_id: projects/grayc-infrastructure/locations/europe/keyRings/sops/cryptoKeys/fluxcd
      created_at: "2025-03-31T14:36:39Z"
      enc: CiQAIt230Nq0ox9LaK6GRfH35U6onpZMxPqYZ+u+L8LSUrsT4OASSQD2lEBU+YT0qTZPAwOlibW55w01cegHIbvgti0tDCcI/m6BXyaBBhndlesY6ZLwrt/6Af2deAlgfnh1h3zVlq2FuHtGEi1Sh24=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-04-02T12:38:49Z"
  mac: ENC[AES256_GCM,data:1me5Oldt7W8In/HeLSumY2swAfx/VWdF3CwHy24+f6H7vaFMbJowh8gGpdVos4rEjgj9rJWMZOgdRAks/o4FpBqcbGPEOGRjOpmQC/HvS5FgSfQzXqLl7w7Sq5mvxp8DyrFg1S3fQq1Jhp44Iuq7fmnh/pKF228L9y3jbwjRGTg=,iv:AyrjJT6FFZEA3Pbq60aD2XqH8YOTHhFkqixMqffxFdI=,tag:WIvxu/OEohEXCzvJNjqE/Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
