micronaut:
  application:
    name: ${project.artifactId}
    version: ${project.version}

  ## see https://docs.micronaut.io/latest/guide/index.html#staticResources
  router:
    static-resources:
      openapi:
        paths: classpath:openapi
        mapping: /openapi/**

  ## see https://docs.micronaut.io/latest/guide/index.html#cors
  server:
    cors:
      enabled: true
      default:
        allowedMethods:
          - GET
          - POST
          - PATCH
          - DELETE

  ## see https://micronaut-projects.github.io/micronaut-security/latest/guide/#interceptUrlMap
  security:
    intercept-url-map:
      - pattern: /endpoints/**
        access: isAnonymous()
      - pattern: /openapi/spec.yaml
        access: isAnonymous()
      - pattern: /**
        access: isAuthenticated()

## see https://docs.micronaut.io/latest/guide/index.html#providedEndpoints
endpoints:
  all:
    path: /endpoints
    sensitive: false
  health:
    details-visible: ANONYMOUS

## see https://docs.micronaut.io/latest/guide/index.html#jsonBinding
jackson:
  serialization:
    writeDatesAsTimestamps: false

## see https://micronaut-projects.github.io/micronaut-sql/latest/guide/#jdbc
datasources:
  default:
    url: jdbc:h2:mem:${datasources.default.database};MODE=PostgreSQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    database: tenant-service
    username: tenant-service
    password: changeMe
    dialect: POSTGRES

## see https://micronaut-projects.github.io/micronaut-flyway/latest/guide/index.html#additionalConfig
flyway:
  datasources:
    default:
      locations: classpath:database

## see https://micronaut-projects.github.io/micronaut-kafka/latest/guide
kafka:
  producers:
    default:
      key:
        serializer: org.apache.kafka.common.serialization.StringSerializer
      value:
        serializer: io.cloudevents.kafka.CloudEventSerializer
