namespace: grayc-inoa-qas
resources:
  - ../../../base/grafana
  - datasources
  - secrets.yaml

labels:
  - pairs:
      grafana-instance: grafana-inoa-qas

patches:
  - target:
      kind: GrafanaFolder
    patch: |-
      - op: add
        path: /spec/instanceSelector
        value:
          matchLabels:
            grafana-instance: grafana-inoa-qas
  - target:
      kind: GrafanaDashboard
    patch: |-
      - op: add
        path: /spec/instanceSelector
        value:
          matchLabels:
            grafana-instance: grafana-inoa-qas
