namespace: grayc-inoa-qas
resources:
  - ../../../base/grafana
  - datasources
  - secrets.yaml

labels:
  - pairs:
      grafana-instance: grafana-inoa-qas

patches:
  - target:
      kind: GrafanaFolder
    patch: |-
      - op: replace
        path: /spec/instanceSelector/matchLabels/grafana-instance
        value: grafana-inoa-qas
