namespace: grayc-inoa-qas
resources:
  - ../../../base/grafana
  - datasources
  - secrets.yaml

patches:
  - target:
      kind: Grafana
      name: grafana
    patch: |-
      - op: replace
        path: /metadata/labels/grafana-instance
        value: grafana-inoa-qas
  - target:
      kind: GrafanaFolder
    patch: |-
      - op: replace
        path: /spec/instanceSelector/matchLabels/grafana-instance
        value: grafana-inoa-qas
