apiVersion: v1
kind: Secret
metadata:
    name: grafana-env
    labels:
        app: grafana
type: Opaque
data:
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:sfPbsfmBTwUJxzdwxvt9WxwuhEufGA==,iv:0dnsmi4W54VC6aRgBGE+opc+aOLMI+Cd/bVk8H9CseY=,tag:QIs57kFLdKqBSPkdHNY/gg==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ZQJwla8pEv5rWMJ73Sm1mydv9l0WtA==,iv:pz/TvvZeTzX64b7IAs6TW8m7nrHRuf2q5xqjBO8+rlc=,tag:r3lF53GrsZS2iHOGx3tv0A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/grayc-infrastructure/locations/europe/keyRings/sops/cryptoKeys/fluxcd
          created_at: "2025-03-24T16:13:50Z"
          enc: CiQAIt230HOpz1xpj6ncZUfBe4y4ZntNPwYAnBqFN3IiJnUld6oSSQD2lEBU4N6FhEYCA5vBqy/Qz8Y84aaU/tmOqiUnGETk7HEa/h7N+ItBAMS701zdtnLodnCVikWeIQ2HEoE2hDOmNzN31HzUhlU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-24T16:13:50Z"
    mac: ENC[AES256_GCM,data:obzrfkwYFJyw2puf5UbBk5F3MMrEKvrPa9kuXItCzv9//vyXs4QDScUws78c0JQWdfB5yPd/W7R78l6rWqPEOZCCnoIO+0mTiQ+6Rek3Y1x3Oo2K0yRrAYba2sQaHwYIMDP2czE0f1iPAmTYUAB8G5wvj9rci83riTwZRSrvR0g=,iv:R0tYLGUueFh7a9RxPecB3g4kiHZc5qvXkHIqvCDiEwQ=,tag:gqUzojvi84ynLEkhDmot6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
