apiVersion: v1
kind: Secret
metadata:
    name: grafana-env
    labels:
        app: grafana
type: Opaque
stringData:
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:az+cJ66eFxbSJ0lgTbDeiw26yYtaMg==,iv:NAua/7ByPeBGX5wvFmjdGEs2PVdpvONoKa5j+HXoXGY=,tag:DAeMgwF0tbtKculoZLT/nA==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8M4h34Hs0OaNWLHM7wsiKNUYk5slYw==,iv:/uVrWClZ19lvjq3ugOepWdbaMZTj7L5q0RkLhOVxXMI=,tag:yr8eUvQKgThSWRusKbUa7Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/grayc-infrastructure/locations/europe/keyRings/sops/cryptoKeys/fluxcd
          created_at: "2025-03-24T16:13:50Z"
          enc: CiQAIt230HOpz1xpj6ncZUfBe4y4ZntNPwYAnBqFN3IiJnUld6oSSQD2lEBU4N6FhEYCA5vBqy/Qz8Y84aaU/tmOqiUnGETk7HEa/h7N+ItBAMS701zdtnLodnCVikWeIQ2HEoE2hDOmNzN31HzUhlU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-31T08:41:47Z"
    mac: ENC[AES256_GCM,data:Xh1syzqr0u59AwIh3GN6MXjFPrfOAre0T5XaOqIaWwbf7qvlu7lN10NXqK1MVcJFD1er2db0rOOt33C43cYeXgqVwDuPcVAq7clhXJYTPZY2m/RK3ddPbHwRfKgVEK53u7//ILFKalYDWDIfpycFu3W8MP1HxSvFHGAfOyKXrVs=,iv:hbqOE5f4eaVOWi3IUzNKTrQKN/dOA5YRb8RmDe2KL7o=,tag:TL4ibD8YI+FzKzEdFibF0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
