apiVersion: v1
kind: Secret
metadata:
    name: grafana-env
    labels:
        app: grafana
type: Opaque
stringData:
    GF_DATABASE_HOST: ENC[AES256_GCM,data:0qNF2Borq4c=,iv:kNK3RHzh3vf+EyYThgnXcK128Mh1m2oowqlr8wfH00U=,tag:n3sBifzreIfXcvsJQ1tjyg==,type:str]
    GF_DATABASE_USER: ENC[AES256_GCM,data:CKIlkVDgfQ==,iv:Hc3WiRqWgYVjOHB2rTDLdZabFAnJitdeXSF7xuKbJOY=,tag:B8OoOtkJBNZtj/aubioa2w==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:iRRcYXa96/yBCLl7Gw5Q5LuzY5Hxzg==,iv:GuZCkLpDrvmG2BwCDnUlpm+Jkum7JsRy44NrbJDLw9o=,tag:p/yR8psp9Xz/YSm/azggJQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:k8aPDK9jTgqU4CloYc8XCZFW9rftsA==,iv:ruJQBnOn7+5UFYIIGT4DWzo48EngSJm5J3bZBuYtgwM=,tag:XZH74nGGxQru7OFZ2F0uUA==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:3nD/6V6wO2625GHgreDKywGB6iQ=,iv:g6HyD7ZHZiqU6j+E/hA4NZjnAeBE0fX4dlCJa90a9x0=,tag:PuhFqUHHzY6abRENg9Sn3g==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/grayc-infrastructure/locations/europe/keyRings/sops/cryptoKeys/fluxcd
          created_at: "2025-08-25T17:01:51Z"
          enc: CiQAIt230LrziZK7jM4guEJJ+a6feiXVYNHdPp3OlBj64uaP9hQSSQD2lEBULOeF/94oEW2xZLbmku2ulDeDK3LeW267Aa7yBLJH7laWAkO4B3GTOxPKHV1rlCJ94zTGA5M6vTmRc/RH+6GLp65gjec=
    lastmodified: "2025-08-25T17:01:52Z"
    mac: ENC[AES256_GCM,data:Fdo3pZQhIi9YSKRAi9LziNcQvlZQv/yHVQ4X6ElSkx46JGQAt5nBN4byu11o6DGV2XLxOm6CtoN+GJLF9+/XDl30TCaaeVK4zuswyMDgaaKU0Qz+TC46FXPsdX8SinhiYUiHNzywLw1FXTB96JRxkP0cK1HVLj0/HXq6JE9+jqE=,iv:YBuTIbFZNjPm4Rj4cHVCflh27IrcFJsGbeRvOLqRyas=,tag:dyHXGYnfANhijEzEpWKBxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.0
