apiVersion: v1
kind: Secret
metadata:
  name: grafana-env
  labels:
    app: grafana
type: Opaque
stringData:
  GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:8bk/xavR7ly85p+wF/hP+jY/JbcOfA==,iv:7VXOpSFPnOyOSs4Q5L6L0Lh+Xj9toAKgvfDwuFKmbbA=,tag:DUcbuygvnUGlSsm6uh/dpg==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:BNeI2ME5hR9FlOf3SYQKe0KYdz62WA==,iv:9G/ih2j/12tIWp7gGX/1pU0wsGKOJGoScrx2jnj3UpE=,tag:YZUNs+jcTONM7dI5PuIZOQ==,type:str]
sops:
  kms: []
  gcp_kms:
    - resource_id: projects/grayc-infrastructure/locations/europe/keyRings/sops/cryptoKeys/fluxcd
      created_at: "2025-04-02T12:33:05Z"
      enc: CiQAIt230B0ZizVooUkGMzOFd41xduq9MAUDQOcMOEAjRJ6JH6oSSQD2lEBUYPzkPwWGK0olWMvamvnsl5mLpZIG/35IzZRxqWKO81Gp1q3rbcSMbuGo3E08Rd47n7p4+FwyfJFN7mcWqGrr2Kdy37M=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-04-02T12:40:02Z"
  mac: ENC[AES256_GCM,data:cgDHB8hoicm9bp8yuTT1wZCsIzeZEyi1qobrea1sCIAuDtr9Gjn0MmUdPp4vvRKD1BqidUmDbUcKjDwS5sRAg46eMLdIORP0bhekliDvLMb+VJxekGAvZn3XAqQQV3knYuw5gmsPWOHs0cmHQpb2zX4s0HE6pFpoUVrk/NNKU+M=,iv:pbJzy3yuxjW0fy3iSG1ZubRxAiCin3ysOWW2nvGw2gE=,tag:mXboPJPy7+XRdYvZ6EWusw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
