apiVersion: v1
kind: Secret
metadata:
    name: grafana-env
    labels:
        app: grafana
type: Opaque
stringData:
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:Hio8N/bM9VQ/VH8aY7yoh23D7AUL2Q==,iv:RdW1w4j7DkHau524mfVr2PDzmz5621xkRhTECplfjsk=,tag:iBzenuo7IlBre3M+iSzM2Q==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:sTgz1qfKxbdUxkRYY+AZUlHiozOAJg==,iv:zLT9ljtA+zBC3dm/xWwm61nH09PjOYVCr082OYm3tj8=,tag:kH9UTCbxV+qWF+21bHMbSw==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:ZDGkr/ksMYMzgpM/JAcds9O6w+w=,iv:NplE71G/Edz2GHvHhcta2A0/2jvKkEroU+P3FIVPf24=,tag:AHhEWlYbS2EYUp1xCbC0Hg==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/grayc-infrastructure/locations/europe/keyRings/sops/cryptoKeys/fluxcd
          created_at: "2025-07-08T11:23:36Z"
          enc: CiQAIt230JU8zJBxd0//KrsgVJV3haineVEhL1Z9mNJl9XwnKUISSQD2lEBU8wApRGhf01++VCFGd0aLnYbCsIDgAaJ6vKamlsZXDCCZXdmg9tMEGCpx5JD/jZq71NfXBujZ/+qcbCnDQBJJntzG16E=
    lastmodified: "2025-07-08T11:23:37Z"
    mac: ENC[AES256_GCM,data:9QZ/FYKO8egb4X9MVj0OWEx0WgME/B61HSUqCfSp/NY8DPoJNwVrM4Zj6f67SyI6FdaGUDkdTsjx8VNfgYVMrEoSHM2cZxiycRfE1luHkBil4cnpHpCDvXskI+fTXUgTPm9qIsswYVWIxGVxXdkVLdCmFAF/C5V8e5pFpRa2x3c=,iv:oX4Dv4iWdG6l/Zq1g23SAklx+ZJqK6NvygKUwr4nxPQ=,tag:oeBfUh7VG5e0Hxh3vKabjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.0
