when:
  event: [manual, push]
  branch: main
  path: [.woodpecker/deploy.yaml, .woodpecker/maven/**, api/**, app/**, service/**, pom.xml, lombok.config, Dockerfile*]

steps:

  deploy:
    image: kokuwaio/buildctl:v0.23.2
    settings:
      platform: linux/amd64
      build-args:
        MAVEN_MIRROR_CENTRAL: ${MAVEN_MIRROR_CENTRAL}
        YARN_NPM_REGISTRY_SERVER: ${YARN_NPM_REGISTRY_SERVER}
        YARN_UNSAFE_HTTP_WHITELIST: ${YARN_UNSAFE_HTTP_WHITELIST}
      name: ghcr.io/inoa-io/inoa:snapshot
      auth:
        ghcr.io:
          username: {from_secret: GHCR_USERNAME}
          password: {from_secret: GHCR_PASSWORD}

  restart:
    image: ghcr.io/grayc-de/plugins/kubectl
    environment:
      # stored as repo secret in https://ci.grayc.io/repos/inoa/cloud/settings
      # definition: https://git.grayc.io/grayc/inoa/src/branch/main/fluxcd/live/dev/service-account/rbac.yaml
      # token: kubectl --context=live --namespace=grayc-inoa-qas get secret restarter -ojson | jq -r .data.token | base64 -d
      CLUSTER_TOKEN: {from_secret: KUBE_TOKEN}
    commands:
      - echo $CLUSTER_LIVE_CERTIFICATE | base64 -d > ca-certificate
      - kubectl config set-cluster grayc-live --server=$CLUSTER_LIVE_HOST --certificate-authority=ca-certificate
      - kubectl config set-credentials restarter --token=$CLUSTER_TOKEN
      - kubectl config set-context default --cluster=grayc-live --namespace=grayc-inoa-qas --user=restarter
      - kubectl config use-context default
      - kubectl version
      - kubectl rollout restart deployment/inoa
      - kubectl rollout status deployment/inoa --timeout=10m
