when:
  - event: manual
    path:
      include:
        - .woodpecker/plugin.yaml
        - .woodpecker/plugin/*
  - event: push
    branch: main
    path:
      include:
        - .woodpecker/plugin.yaml
        - .woodpecker/plugin/*
steps:
  build:
    image: ghcr.io/grayc-de/plugins/kaniko
    environment:
      DOCKER_CONFIG_JSON: {from_secret: DOCKER_CONFIG_JSON}
    settings:
      context: .woodpecker/plugin
      destination: ghcr.io/grayc-de/plugins/inoa

  check:
    image: ghcr.io/grayc-de/plugins/inoa
    privileged: true
    backend_options:
      kubernetes:
        securityContext:
          privileged: true
    pull: true
    commands:
      - dockerd-start
      - java --version
      - mvn --version
      - node --version
      - yarn --version
      - docker version
