when:
  - event: [manual, push, pull_request]
    path:
      - .woodpecker/techdocs.yaml
      - docs/techdocs/**
    branch: main

steps:
  generate:
    image: ghcr.io/grayc-de/techdocs
    environment:
      DOCKER_CONFIG_JSON: {from_secret: DOCKER_CONFIG_JSON}
    entrypoint:
      [
        /techdocs/entrypoint-generate.sh,
        --source-dir,
        docs/techdocs,
        --output-dir,
        docs/target,
      ]

  publish:
    image: ghcr.io/grayc-de/techdocs
    environment:
      PUBLISH_TECHDOCS_SECRET: {from_secret: GRAYC_TECHDOCS}
      DOCKER_CONFIG_JSON: {from_secret: DOCKER_CONFIG_JSON}
    entrypoint:
      [
        /techdocs/entrypoint-publish.sh,
        --publisher-type,
        googleGcs,
        --storage-name,
        grayc-techdocs,
        --entity,
        inoa/System/inoa-cloud,
        --directory,
        docs/target,
      ]
    when:
      - event: [manual, push]
        branch: main
