when:
  - event: pull_request
  - event: manual
    branch:
      exclude: [mains]

services:
  - name: inoa-dockerd-verify
    image: ghcr.io/grayc-de/plugins/dockerd
    privileged: true
    # 2375 docker rest api
    # 6443 k3s controll plane
    # 8080 k3s http api
    # 8883 k3s mqtt api
    ports: [2375, 6443, 8080, 8883]

variables:
  - &defaults
    image: ghcr.io/grayc-de/plugins/maven
    depends_on: []
    environment:
      - DOCKER_HOST=tcp://inoa-dockerd-verify:2375
      - TESTCONTAINERS_RYUK_DISABLED=true
    pull: false
    when:
      path:
        - api/**
        - app/**
        - service/**
        - image/**
        - test/**
        - pom.xml
        - lombok.config

steps:

  # speed up later steps by preloading used images
  preload-images:
    <<: *defaults
    commands:
      - mkdir $HOME/.docker && echo "$DOCKER_CONFIG_JSON" > $HOME/.docker/config.json
      # docker build
      - docker pull --quiet docker.io/library/debian:stable-slim &
      - docker pull --quiet docker.io/eclipse-temurin:17-jre &
      # test containers
      - docker pull --quiet docker.io/library/postgres:15.4 &
      - docker pull --quiet docker.io/library/influxdb:2.1.1-alpine &
      - docker pull --quiet docker.io/confluentinc/cp-kafka:6.2.6 &
      # integration tests
      - docker pull --quiet docker.io/rancher/k3s:v1.24.12-k3s1 &
      - docker pull --quiet ghcr.io/grayc-de/kafka:3.6.1 &
      - wait
    secrets: [DOCKER_CONFIG_JSON]

  build-api:
    <<: *defaults
    commands: [mvn -Dcheck.skip install -pl api -am]
  build-service:
    <<: *defaults
    depends_on: [build-api]
    commands: [mvn -Dcheck.skip -Dmaven.test.skip install -pl service]
  build-app:
    <<: *defaults
    commands: [mvn -Dcheck.skip -Dmaven.test.skip install -pl app]

  test-service:
    <<: *defaults
    depends_on: [build-service]
    commands:
      - DOCKER_HOST=tcp://$(docker run --rm --network host debian:stable-slim hostname -I | tr ' ' '\n' | grep 10.42):2375
      - mvn -Dcheck.skip test -pl service -Dsurefire.rerunFailingTestsCount=2
    when: [path: [pom.xml, api/**, service/**]]
  test-app:
    <<: *defaults
    depends_on: [build-app]
    commands: [mvn -Dcheck.skip test -pl app]
    when: [path: [app/**]]

  image:
    <<: *defaults
    depends_on: [build-service, build-app]
    commands: [mvn -Dcheck.skip install -pl image]

  integration-prepare:
    <<: *defaults
    depends_on: [build-api]
    commands: [mvn -Dcheck.skip -pl test pre-integration-test -Dk3s.dockerImages= -Dk3s.skipApply]
  integration-test:
    <<: *defaults
    depends_on: [image, integration-prepare]
    commands: [mvn -Dcheck.skip -pl test integration-test -Dk3s.failIfExists=false -Dk3s.ip=$INOA_DOCKERD_VERIFY_SERVICE_HOST]
  integration-errors:
    <<: *defaults
    depends_on: [integration-test]
    commands:
      - docker ps -a
      - docker logs k3s-maven-plugin
    when: [status: [failure]]
