when:
  event: [manual, pull_request]
  path: [.woodpecker/verify.yaml, api/**, app/**, service/**, image/**, pom.xml, lombok.config]

services:
  - name: dockerd
    image: kokuwaio/dockerd
    ports: [2375]
    privileged: true

steps:

  build: &maven
    image: ghcr.io/grayc-de/plugins/inoa
    depends_on: []
    environment:
      MAVEN_ARGS: --batch-mode --settings=.woodpecker/maven/settings.xml --color=always --no-transfer-progress
    commands: mvn -am -pl service -DskipTests -DskipITs install

  test-yarn:
    image: ghcr.io/grayc-de/plugins/node:20-chrome
    depends_on: [build]
    directory: app
    commands:
      - yarn config --no-defaults
      - yarn install --immutable
      - yarn lint
      - yarn test --no-watch --no-progress
    when: [path: [app/**]]

  test-service:
    <<: *maven
    depends_on: [build]
    commands:
      # testcontainers uses random ports and service only expose named ports, use pod ip
      # another solution: use fixed posts in ci and expose via dockerd service
      - DOCKER_HOST=tcp://$(docker run --rm --network host debian:stable-slim hostname -I | tr ' ' '\n' | grep 10.):2375
      - mvn test -pl service -Dsurefire.rerunFailingTestsCount=2
    when: [path: [pom.xml, api/**, service/**]]

  image:
    <<: *maven
    depends_on: [build]
    commands: mvn install -pl image

  integration-test:
    <<: *maven
    depends_on: [image]
    commands:
      - DOCKER_IP=$(docker run --rm --network host debian:stable-slim hostname -I | tr ' ' '\n' | grep 10.)
      - DOCKER_HOST=tcp://$DOCKER_IP:2375
      - mvn -pl test verify -Dinoa.domain=$DOCKER_IP.nip.io
    when:
      path: {exclude: [app/**]}

  integration-errors:
    <<: *maven
    depends_on: [integration-test]
    commands:
      - docker logs k3s-maven-plugin
      - docker exec k3s-maven-plugin kubectl get all --all-namespaces --output=wide
      - docker exec k3s-maven-plugin ls /var/log/containers
      - docker exec k3s-maven-plugin sh -c 'cat `find /var/log/containers -name inoa-*_wait-for-keycloak-*.log`'
      - docker exec k3s-maven-plugin sh -c 'cat `find /var/log/containers -name inoa-*_wait-for-postgres-*.log`'
      - docker exec k3s-maven-plugin sh -c 'cat `find /var/log/containers -name inoa-*_inoa-*.log`'
    when:
      path: {exclude: [app/**]}
      status: failure
