when:
  event: [manual, pull_request]
  path: [.woodpecker/verify.yaml, .woodpecker/maven/**, api/**, app/**, service/**, image/**, pom.xml, lombok.config]

services:
  - name: dockerd
    image: kokuwaio/dockerd
    ports:
      - 2375  # docker rest api
      - 5432  # testcontainers postgres
      - 8086  # testcontainers influxdb
      - 6443  # k3s control plane
      - 8080  # k3s http api
      - 8883  # k3s mqtt api
    privileged: true

steps:

  build: &maven
    image: ghcr.io/grayc-de/plugins/maven:3-jdk21
    depends_on: []
    environment:
      MAVEN_ARGS: --batch-mode --settings=.woodpecker/maven/settings.xml --color=always --no-transfer-progress
    commands: mvn -am -pl service -DskipTests -DskipITs install

  test-yarn:
    image: kokuwaio/node:20-chrome
    depends_on: [build]
    directory: app
    commands:
      - yarn config --no-defaults
      - yarn install --immutable
      - yarn lint
      - yarn test --no-watch --no-progress
    when: [path: [app/**]]

  test-service:
    <<: *maven
    depends_on: [build]
    commands: mvn test -pl service -Dsurefire.rerunFailingTestsCount=2
    when: [path: [pom.xml, api/**, service/**]]

  image:
    <<: *maven
    depends_on: [build]
    commands: mvn install -pl image

  integration-test:
    <<: *maven
    depends_on: [image]
    commands: mvn -pl test verify -Dinoa.domain=$(env|grep DOCKERD_SERVICE_HOST|cut -d= -f2).nip.io
    when:
      path: {exclude: [app/**]}

  integration-errors:
    <<: *maven
    depends_on: [integration-test]
    commands:
      - docker logs k3s-maven-plugin
      - docker exec k3s-maven-plugin kubectl get all --all-namespaces --output=wide
      - docker exec k3s-maven-plugin ls /var/log/containers
      - docker exec k3s-maven-plugin sh -c 'cat `find /var/log/containers -name inoa-*_wait-for-keycloak-*.log`'
      - docker exec k3s-maven-plugin sh -c 'cat `find /var/log/containers -name inoa-*_wait-for-postgres-*.log`'
      - docker exec k3s-maven-plugin sh -c 'cat `find /var/log/containers -name inoa-*_inoa-*.log`'
      - exit 1
    when:
      path: {exclude: [app/**]}
      status: failure
