when:
  event: [manual, pull_request]
  path: [.woodpecker/verify.yaml, .woodpecker/maven/**, api/**, app/**, service/**, pom.xml, lombok.config, Dockerfile*]

services:
  - name: dockerd
    image: kokuwaio/dockerd
    ports:
      - 2375  # docker rest api
      - 5432  # testcontainers postgres
      - 8086  # testcontainers influxdb
      - 6443  # k3s control plane
      - 8080  # k3s http api
      - 8883  # k3s mqtt api
    privileged: true

steps:

  image:
    image: kokuwaio/docker-cli
    depends_on: []
    commands:
      - docker buildx create --use --name=buildkit --driver=remote --driver-opt=default-load=true $BUILDKIT_HOST
      - docker buildx build .
            --tag=ghcr.io/inoa-io/inoa:snapshot
            --build-arg=MAVEN_MIRROR_CENTRAL
            --build-arg=YARN_NPM_REGISTRY_SERVER
            --build-arg=YARN_UNSAFE_HTTP_WHITELIST

  maven:
    image: docker.io/library/maven:3.9.10-eclipse-temurin-21@sha256:193ed19a4806b4bbad65b2e8a2a9bbf901b6e216eb0d5761c70c2c4537cd53d7
    depends_on: []
    commands: mvn install --settings=$CI_WORKSPACE/.woodpecker/maven/settings.xml
    when: [path: {exclude: [app/**]}]

  yarn:
    image: kokuwaio/node:20-chrome
    depends_on: []
    directory: app
    commands:
      - yarn config --no-defaults
      - yarn install --immutable
      - yarn lint
      - yarn test --no-watch --no-progress
    when: [path: [.woodpecker/verify.yaml, app/**]]

  integration-prepare:
    image: ghcr.io/grayc-de/plugins/maven:3-jdk21
    # replace with default maven image when k3s-maven-plugin 2.0.0 is released which does not need local docker-cli
    # image: docker.io/library/maven:3.9.9-eclipse-temurin-21@sha256:933900d8738eab72ddebb7ad971fc9bca91ae6bc4c7b6d6bbc17fb3609f5e64b
    depends_on: []
    directory: test
    commands: mvn --settings=$CI_WORKSPACE/.woodpecker/maven/settings.xml k3s:run k3s:image -Dk3s.dockerImages=
    when: [path: {exclude: [app/**, api/src/test/**, service/src/test/**]}]

  integration-test:
    image: ghcr.io/grayc-de/plugins/maven:3-jdk21
    # replace with default maven image when k3s-maven-plugin 2.0.0 is released which does not need local docker-cli
    # image: docker.io/library/maven:3.9.9-eclipse-temurin-21@sha256:933900d8738eab72ddebb7ad971fc9bca91ae6bc4c7b6d6bbc17fb3609f5e64b
    depends_on: [image, integration-prepare]
    directory: test
    commands: mvn --settings=$CI_WORKSPACE/.woodpecker/maven/settings.xml verify -Dip="$(docker run --rm --network host debian:stable-slim hostname -I | tr ' ' '\n' | grep 10.42)"
    when: [path: {exclude: [app/**, api/src/test/**, service/src/test/**]}]

  integration-errors:
    image: kokuwaio/docker-cli
    depends_on: [integration-test]
    commands:
      - docker logs k3s-maven-plugin
      - docker exec k3s-maven-plugin kubectl get all --all-namespaces --output=wide
      - docker exec k3s-maven-plugin ls /var/log/containers
      - docker exec k3s-maven-plugin sh -c 'cat `find /var/log/containers -name inoa-*_wait-for-keycloak-*.log`'
      - docker exec k3s-maven-plugin sh -c 'cat `find /var/log/containers -name inoa-*_wait-for-postgres-*.log`'
      - docker exec k3s-maven-plugin sh -c 'cat `find /var/log/containers -name inoa-*_inoa-*.log`'
      - exit 1
    when:
      path: {exclude: [app/**, api/src/test/**, service/src/test/**]}
      status: failure
