when:
  - event: pull_request
  - event: manual
    branch:
      exclude: [main]

variables:
  - &when-path
    path: [api/**, app/**, service/**, image/**, test/**, pom.xml, lombok.config]
  - &maven
    image: ghcr.io/grayc-de/plugins/maven
    depends_on: []
    environment: [DOCKER_HOST=tcp://inoa-dockerd-verify:2375, TESTCONTAINERS_RYUK_DISABLED=true]
    when:
      <<: *when-path
  - &node
    image: ghcr.io/grayc-de/plugins/node:20
    depends_on: []
    directory: app
    when:
      <<: *when-path

services:
  - name: inoa-dockerd-verify
    image: ghcr.io/grayc-de/plugins/dockerd
    privileged: true
    # 2375 docker rest api
    # 6443 k3s controll plane
    # 8080 k3s http api
    # 8883 k3s mqtt api
    ports: [2375, 6443, 8080, 8883]
    when: {<<: *when-path}

steps:

  # speed up later steps by preloading used images
  preload-images:
    <<: *maven
    commands:
      - mkdir $HOME/.docker && echo "$DOCKER_CONFIG_JSON" > $HOME/.docker/config.json
      # docker build
      - docker pull --quiet docker.io/library/debian:stable-slim &
      - docker pull --quiet docker.io/eclipse-temurin:17-jre &
      # test containers
      - docker pull --quiet docker.io/library/postgres:14.11 &
      - docker pull --quiet docker.io/library/influxdb:2.7.5 &
      # integration tests
      - docker pull --quiet docker.io/rancher/k3s:v1.28.6-k3s2 &
      - docker pull --quiet ghcr.io/grayc-de/kafka:3.6.1 &
      - docker pull --quiet ghcr.io/inoa-io/mcnoize:0.0.1 &
      - wait
    secrets: [DOCKER_CONFIG_JSON]
  preload-yarn:
    <<: *node
    commands: [yarn config --no-defaults, yarn install --immutable]

  build-api:
    <<: *maven
    commands: [mvn -Dcheck.skip install -pl api -am]
  build-service:
    <<: *maven
    depends_on: [build-api]
    commands: [mvn -Dcheck.skip -Dmaven.test.skip install -pl service]
  build-app:
    <<: *node
    depends_on: [preload-yarn]
    commands: [yarn build --no-progress --configuration=production]

  test-service:
    <<: *maven
    depends_on: [build-service]
    commands:
      - DOCKER_HOST=tcp://$(docker run --rm --network host debian:stable-slim hostname -I | tr ' ' '\n' | grep 10.42):2375
      - mvn -Dcheck.skip test -pl service -Dsurefire.rerunFailingTestsCount=2
    when: [path: [pom.xml, api/**, service/**]]
  test-app:
    <<: *node
    depends_on: [preload-yarn]
    commands: [yarn test --no-progress --no-watch]
    when: [path: [app/**]]
    failure: ignore  # TODO testing fails :'(

  image:
    <<: *maven
    depends_on: [build-service, build-app]
    commands: [mvn -Dcheck.skip install -pl image]

  integration-prepare:
    <<: *maven
    depends_on: [build-api]
    commands: [mvn -Dcheck.skip -pl test pre-integration-test -Dk3s.dockerImages= -Dk3s.skipApply]
  integration-test:
    <<: *maven
    depends_on: [image, integration-prepare]
    commands: [mvn -Dcheck.skip -pl test verify -Dk3s.failIfExists=false -Dk3s.ip=$INOA_DOCKERD_VERIFY_SERVICE_HOST]
  integration-errors:
    <<: *maven
    depends_on: [integration-test]
    commands:
      - docker ps -a
      - docker logs k3s-maven-plugin
    when:
      <<: *when-path
      status: failure
