when:
  - event: pull_request
  - event: manual
    branch:
      exclude: [mains]

services:
  - name: inoa-dockerd-verify
    image: ghcr.io/grayc-de/plugins/dockerd
    privileged: true
    # 2375 docker rest api
    # 6443 k3s controll plane
    # 8080 k3s http api
    # 8883 k3s mqtt api
    ports: [2375, 6443, 8080, 8883]

variables:
  - &defaults
    image: ghcr.io/grayc-de/plugins/maven
    depends_on: []
    environment:
      - DOCKER_HOST=tcp://inoa-dockerd-verify:2375
      - TESTCONTAINERS_RYUK_DISABLED=true
    pull: false
    when:
      path:
        - inoa-fleet/**
        - inoa-measurement/**
        - inoa-groundcontrol/**
        - inoa-test/**
        - pom.xml
        - lombok.config

steps:

  # speed up later steps by preloading used images
  preload-images:
    <<: *defaults
    commands:
      - docker pull --quiet ghcr.io/graalvm/native-image:muslib-22.3.2 &
      - docker pull --quiet docker.io/eclipse-temurin:17-jre &
      - docker pull --quiet docker.io/curlimages/curl:8.1.2 &
      - docker pull --quiet docker.io/library/node:18-slim &
      - docker pull --quiet docker.io/rancher/k3s:v1.24.12-k3s1 &
      - wait

  build-fleet:
    <<: *defaults
    commands: [mvn -Dcheck.skip -Dmaven.test.skip install -pl inoa-fleet]
  build-measurement:
    <<: *defaults
    commands: [mvn -Dcheck.skip -Dmaven.test.skip install -pl inoa-measurement]
  build-groundcontrol:
    <<: *defaults
    commands: [mvn -Dcheck.skip -Dmaven.test.skip install -pl inoa-groundcontrol]

  test-fleet:
    <<: *defaults
    depends_on: [build-fleet]
    commands:
      - DOCKER_HOST=tcp://$(docker run --rm --network host debian:stable-slim hostname -I | tr ' ' '\n' | grep 10.42):2375
      - mvn -Dcheck.skip test -pl inoa-fleet
    when: [path: [pom.xml, inoa-fleet/**]]
  test-measurement:
    <<: *defaults
    depends_on: [build-measurement]
    commands:
      - DOCKER_HOST=tcp://$(docker run --rm --network host debian:stable-slim hostname -I | tr ' ' '\n' | grep 10.42):2375
      - mvn -Dcheck.skip test -pl inoa-measurement
    when: [path: [pom.xml, inoa-measurement/**]]

  integration-prepare:
    <<: *defaults
    commands: [mvn -Dcheck.skip -pl inoa-test pre-integration-test -Dk3s.tarFiles= -Dk3s.dockerImages= -Dk3s.skipApply]
  integration-test:
    <<: *defaults
    depends_on: [build-fleet, build-measurement, build-groundcontrol, integration-prepare]
    commands: [mvn -Dcheck.skip -pl inoa-test integration-test -Dk3s.failIfExists=false -Dk3s.ip=$INOA_DOCKERD_VERIFY_SERVICE_HOST]
  integration-errors:
    <<: *defaults
    depends_on: [integration-test]
    commands:
      - docker ps -a
      - docker logs k3s-maven-plugin
    when: [status: [failure]]
