apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: postgres
          image: docker.io/library/postgres
          imagePullPolicy: IfNotPresent
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - secretRef:
                name: postgres-env
          ports:
            - name: postgres
              containerPort: 5432
          startupProbe:
            exec:
              command: [/bin/sh, -c, exec pg_isready --user=$POSTGRES_USER]
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 30
          livenessProbe:
            exec:
              command: [/bin/sh, -c, exec pg_isready --user=$POSTGRES_USER]
            failureThreshold: 1
            periodSeconds: 60
          resources:
            limits:
              memory: 2000Mi
            requests:
              cpu: 100m
              memory: 200Mi
          securityContext:
            runAsUser: 999
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          volumeMounts:
            - name: config
              mountPath: /docker-entrypoint-initdb.d/init.sh
              subPath: init.sh
              readOnly: true
            - name: storage
              mountPath: /var/lib/postgresql/data
            - name: tmp
              mountPath: /var/run/postgresql
      enableServiceLinks: false
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: postgres-config
            items:
              - key: init.sh
                path: init.sh
        - name: storage
          persistentVolumeClaim:
            readOnly: false
            claimName: postgres
        - name: tmp
          emptyDir:
            sizeLimit: 100Mi
