apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
spec:
  serviceName: influxdb
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: influxdb
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: influxdb
          image: influxdb:2.3
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: influxdb-environment
            - secretRef:
                name: influxdb-environment
          ports:
            - name: http
              containerPort: 8086
          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 55
          livenessProbe:
            httpGet:
              path: /health
              port: http
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          volumeMounts:
            - name: data
              mountPath: /var/lib/influxdb2
            - name: config
              mountPath: /etc/influxdb2
            - name: tmp
              mountPath: /tmp
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          emptyDir: {}
        - name: tmp
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 1Gi
