labels:
  - pairs:
      app.kubernetes.io/name: kafka-console
      app.kubernetes.io/technology: golang

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: kafka-console-env
    literals:
      - KAFKA_BROKERS=kafka:9092
