name: Snapshot

"on":
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - run: mvn -B dependency:go-offline
      - run: mvn -B install -Djib.to.image.version.suffix=-`date +"%Y%m%d-%H%M%S"` -T1C
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_ACTION_TOKEN }}
      - name: docker push
        run: |
          docker push --all-tags ghcr.io/inoa-io/cnpm-auth-service
          docker push --all-tags ghcr.io/inoa-io/cnpm-tenant-service
          docker push --all-tags ghcr.io/inoa-io/fleet-registry-service
          docker push --all-tags ghcr.io/inoa-io/fleet-registry-hono-bridge
          docker push --all-tags ghcr.io/inoa-io/fleet-gateway-logger
          docker push --all-tags ghcr.io/inoa-io/fleet-gateway-command-service
          docker push --all-tags ghcr.io/inoa-io/fleet-thing-service
          docker push --all-tags ghcr.io/inoa-io/measurement-provisioner
          docker push --all-tags ghcr.io/inoa-io/measurement-telemetry-translator
          docker push --all-tags ghcr.io/inoa-io/measurement-telemetry-exporter
