name: CI

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request: {}

jobs:

  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: colored
          strict: true

  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: avto-dev/markdown-lint@v1
        with:
          args: /github/workspace

  json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: limitusus/json-syntax-check@v1.0.3
        with:
          pattern: \\.json$

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_ACTION_TOKEN }}
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - run: mvn -B dependency:go-offline
      - run: mvn -B install -T1C
