name: CI

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request: {}

jobs:

  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: colored
          strict: true

  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: avto-dev/markdown-lint@v1
        with:
          args: /github/workspace

  kustomize:
    strategy:
      matrix:
        type: [k3s-minimal, k3s-full]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: karancode/kustomize-github-action@v1.3.0
        with:
          kustomize_version: 4.4.0
          kustomize_build_dir: deployment/${{ matrix.type }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
      - uses: docker/login-action@v2.1.0
        if: ${{ github.ref_name == 'main' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_ACTION_TOKEN }}
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - run: mvn -B -ntp dependency:go-offline
      - run: mvn -B -ntp install -Dmaven.test.redirectTestOutputToFile=false -Dsurefire.rerunFailingTestsCount=3 -pl \!test
      - run: mvn -B -ntp install -Dmaven.test.redirectTestOutputToFile=false -Dsurefire.rerunFailingTestsCount=3 -pl test
      - run: mvn -B -ntp jib:build -Djib.to.tags=latest,${{ steps.prep.outputs.BUILD_ID }} -Djib.from.platforms=linux/amd64,linux/arm64 -pl :fleet-registry-service,:fleet-mqtt-broker,:fleet-admin-ui,:fleet-gateway-logger,:measurement-telemetry-translator,:measurement-telemetry-exporter,:gateway-command-service,:fleet-registry-hono-bridge,:fleet-thing-service -T1C
        if: ${{ github.ref_name == 'main' }}
