name: PullRequest

"on": [pull_request]

jobs:

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: colored
          strict: true

  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - run: markdownlint .

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
