name: PullRequest

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      ###
      ### Prepare
      ###

      - name: checkout
        uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      ###
      ### Build
      ###

      - name: setup maven dependencies
        run: mvn -B dependency:go-offline -q
      - name: build
        run: mvn -B clean install
