name: PullRequest

"on": [pull_request]

jobs:

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: colored
          strict: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: mvn -B dependency:go-offline -q
      - run: mvn -B clean install
