name: Lint

"on":
  workflow_dispatch: {}
  push: {}

jobs:

  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: colored
          strict: true

  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://avtodev/markdown-lint:v1
        with:
          args: /github/workspace

  json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
