name: Release

"on":
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - run: mvn -B dependency:go-offline
      - run: mvn -B release:prepare
      - run: mvn -B release:perform
      - name: docker login
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_ACTION_TOKEN }}
      - name: docker push
        if: github.ref == 'refs/heads/main'
        run: |
          docker push --all-tags ghcr.io/grayc-de/inoa/cnpm-auth-service
          docker push --all-tags ghcr.io/grayc-de/inoa/cnpm-tenant-service
          docker push --all-tags ghcr.io/grayc-de/inoa/fleet-registry-service
          docker push --all-tags ghcr.io/grayc-de/inoa/fleet-registry-hono-bridge
          docker push --all-tags ghcr.io/grayc-de/inoa/fleet-gateway-logger
          docker push --all-tags ghcr.io/grayc-de/inoa/fleet-gateway-command-service
          docker push --all-tags ghcr.io/grayc-de/inoa/fleet-thing-service
          docker push --all-tags ghcr.io/grayc-de/inoa/measurement-provisioner
          docker push --all-tags ghcr.io/grayc-de/inoa/measurement-telemetry-translator
          docker push --all-tags ghcr.io/grayc-de/inoa/measurement-telemetry-exporter
