name: Snapshot

"on":
  workflow_dispatch: {}
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - run: mvn -B dependency:go-offline
      - run: mvn -B install -Djib.to.image.version.suffix=-`date +"%Y%m%d-%H%M%S"`
      - uses: dorny/test-reporter@v1
        if: failure()
        with:
          name: surefire
          path: '**/target/surefire-reports/*.xml'
          reporter: java-junit
          list-suites: failed
          list-tests: failed
      - name: docker login
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_ACTION_TOKEN }}
      - name: docker push
        if: github.ref == 'refs/heads/main'
        run: |
          docker push --all-tags ghcr.io/inoa-io/cnpm-auth-service
          docker push --all-tags ghcr.io/inoa-io/cnpm-tenant-service
          docker push --all-tags ghcr.io/inoa-io/fleet-registry-service
          docker push --all-tags ghcr.io/inoa-io/fleet-registry-hono-bridge
          docker push --all-tags ghcr.io/inoa-io/fleet-gateway-logger
          docker push --all-tags ghcr.io/inoa-io/fleet-gateway-command-service
          docker push --all-tags ghcr.io/inoa-io/fleet-thing-service
          docker push --all-tags ghcr.io/inoa-io/measurement-provisioner
          docker push --all-tags ghcr.io/inoa-io/measurement-telemetry-translator
          docker push --all-tags ghcr.io/inoa-io/measurement-telemetry-exporter
