name: Snapshot

"on":
  workflow_dispatch: {}
  push:
    branches:
      - main
      - '*.x'

jobs:

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: colored
          strict: true

  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://avtodev/markdown-lint:v1
        with:
          args: /github/workspace

  build:
    runs-on: ubuntu-latest
    needs:
      - lint-markdown
      - lint-yaml
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - run: mvn -B dependency:go-offline -q
      - run: mvn -B install -Dcontainer.image.version='${project.version}-${maven.build.timestamp}' -DskipTests
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_ACTION_TOKEN }}
      - run: docker push --all-tags ghcr.io/grayc-de/gateway-registry
      - run: docker push --all-tags ghcr.io/grayc-de/gateway-registry-hono-bridge
      - run: docker push --all-tags ghcr.io/grayc-de/gateway-command-service
      - run: docker push --all-tags ghcr.io/grayc-de/inoa-translator
      - run: docker push --all-tags ghcr.io/grayc-de/inoa-exporter
      - run: docker push --all-tags ghcr.io/grayc-de/external-authorization
      - run: docker push --all-tags ghcr.io/grayc-de/gateway-logger
